### ISSUE TITLE
Separate the Test project into its own?

### ISSUE THREAD

**Issue by branflake2267** [branflake2267/GWT-Maps-V3-Api#10]
I wonder if we should make the test project its own repo and move the api source then up one folder to make the setup easier. Would this screw up the maven paths?

**Comment by twistedpair** [comment]
Just need to make a parent project for the whole thing. That is how most Maven projects do it (parent POM). For example, the Emma Ecl Eclipse code coverage plugin: https://eclemma.svn.sourceforge.net/svnroot/eclemma/eclemma/trunk/ .

I've gotten it working tonight, but it has vex the git/Eclipse integration. Need to figure that our before merging it.

**Comment by twistedpair** [comment]
OK, you should be able to build as single project now, with two sub projects. Just need to give them better names now.

Updated instructions in [Eclipse Contributor Setup](https://github.com/branflake2267/GWT-Maps-V3-Api/wiki/Eclipse-Contributor-Setup). Let me know if they work for you.

**Comment by branflake2267** [comment]
I seem to figure out how to setup the project by using import in egit and its pretty easy as it stands now. So I'm not sure its needed? Thoughts?

**Comment by twistedpair** [comment]
Which part is not needed, or do you mean the whole section? I'm happy with anything you want to do to it. Hopefully if you're contributing, you know how to do a Git checkout and import an Eclipse project.

**Comment by branflake2267** [comment]
My bad, I think I misunderstood. What you have is great. I was thinking of the physical code separation thought I had in the very beginning. Your docs are great. I was thinking when I imported the git repo into egit, then I right click and import projects, then I reinit the project to get the libs into the war for my testing worked great.

**Comment by twistedpair** [comment]
Checked in. I plan to change up the names a little bit, to
- gwt-maps-api-v3-core
- gwt-maps-api-v3-demo

So that the parent can be `gwt-maps-api-v3` . I just did this on my local copy, but it seems to have annoyed Eclipse. Will get it right, then check it in and close this issue out.

**Comment by twistedpair** [comment]
The showcase project is already in its own Maven project, but I'll apply these naming conventions in the v3.9 branch.
