### ISSUE TITLE
Showcase on gonevertical-apis.appspot.com is not working

### ISSUE THREAD

**Issue by p91paul** [branflake2267/GWT-Maps-V3-Api#106]
It doesn't show anything, reporting 
404 Not Found - http://gonevertical-apis.appspot.com/showcase/showcase.nocache.js
on the browser console.

**Comment by branflake2267** [comment]
Thanks for reporting that. I'll get that fixed asap.

**Comment by branflake2267** [comment]
http://gonevertical-apis.appspot.com/ is back up. I caused some sorrow when configuring the pom.xml for signing a release.
