### ISSUE TITLE
Figure out how to keep the __gwt_Object

### ISSUE THREAD

**Issue by branflake2267** [branflake2267/GWT-Maps-V3-Api#11]
The __gwt_object is used in chrome so it doesnt register duplicate objects. I'd like to figure out why it is throwing and then try to keep it's use. I think the map api uses some sort of call back and doesn't dig it.

**Comment by twistedpair** [comment]
Is it the Map JS API or the Web Services? The only time it has given me issues is with remote requests. I bet Google rejects requests with invalid parameters.

How about we check before building requests for !GWT.isScript() and in that conditional strike the _gwt_X offender from the request, but leave it on the original object?

**Comment by branflake2267** [comment]
I'm thinking this has to do with getting stuck in the callback maps web services I think. I'm having a hard time recalling. I've been told this should only happen in chrome debugging and this object is stuck in to work around the sandbox, but I'm a little unclear exactly. I think you have the right idea leave it if we can and remove it only from the offending calls.

**Comment by branflake2267** [comment]
Its used so the objects don't re-register them selfs or something like that

**Comment by twistedpair** [comment]
Moved to Issue #46 as this will be the fix.
