### ISSUE TITLE
Wrong method signature in Projection.fromPointToLatLng

### ISSUE THREAD

**Issue by idegregorio** [branflake2267/GWT-Maps-V3-Api#117]
The method Projection.fromPointToLatLng should return a LatLng, it currently (3.16) returns a Point

**Comment by branflake2267** [comment]
Thanks for reporting :) I'll fix this tomorrow. I'm going to work on a new release tomorrow.

**Comment by branflake2267** [comment]
Fix in the works. I should have this deployed tomorrow.

**Comment by branflake2267** [comment]
I've updated the test cases for this.

**Comment by branflake2267** [comment]
Fixed in source, closing and releasing tomorrow.
