### ISSUE TITLE
Place API jars in Maven Central Repo

### ISSUE THREAD

**Issue by twistedpair** [branflake2267/GWT-Maps-V3-Api#12]
Maven is not useful unless you've pushed your jars out publicly. We need to get ours out there.

Rename group id com.github.branflake2267
https://issues.sonatype.org/browse/OSSRH-4661 - notes on sona repo

``` xml
<groupId>com.github.branflake2267</groupdId>
<artifactId>maps-core</artifact>

<groupId>com.github.branflake2267</groupdId>
<artifactId>maps-test</artifact>
```

**Comment by twistedpair** [comment]
I've opened a ticket to get an account for the project on the Sonatype OSS maven repo. That will get it into central. It should go through some time early this week.

**Comment by branflake2267** [comment]
Nice work. :)

**Comment by branflake2267** [comment]
Where you able to get it into the repo? I've added some code which we could host it via github if your interested?

**Comment by twistedpair** [comment]
I've got the Sonatype OSS account, but not raised the ticket. I'll look into what this takes.

**Comment by branflake2267** [comment]
https://issues.sonatype.org/browse/OSSRH-4661 - filed issue

**Comment by twistedpair** [comment]
Their response, as expected:

> Joel Orlina added a comment - 11/07/12 09:14 AM
> The com.google.\* groupIds are reserved for projects from Google itself. Can you use the groupId com.github.branflake2267? Then you could deploy to a sub-group, like com.github.branflake2267.gwt-maps-v3-api

I wonder what it takes to get an account moved/renamed on GitHub? _branflake2267_ is just an odd name to have in all the package names and will make implementers curious. Whatever is chosen will also be a breaking change. It will at least need to be v3.10.0 or higher (can't do 4 since we're mirroring the GMaps versions).

**Comment by branflake2267** [comment]
I asked to see if groupid com.github.GWT-Maps-V3-Api would work

**Comment by branflake2267** [comment]
While I do think my username is odd, I think it make sense in context if you find the repo here. 

I think changing the groupid to com.github.branflake2267.GWT-Maps-V3-Api would be easiest? Do think thats ok?

**Comment by twistedpair** [comment]
I think _com.github.gwt-maps-v3-api_ would be best. This project certainly was your initiative and I don't mean to take anything away from it with the name. I just think that from an API consumer standpoint a more lucid name is better.

Probably something like:

> `<groupId>com.github.gwt-maps-v3-api</groupdId>`
> `<artifactId>maps-core</artifact>`
> 
> `<groupId>com.github.gwt-maps-v3-api</groupdId>`
> `<artifactId>maps-test</artifact>`

And update our packages to `com.github.gwt.maps`  and `com.github.gwt.maps.test`.

What do you think?

**Comment by branflake2267** [comment]
We would have to own that om.github.gwt-maps-v3-api domain name, or account on github. Which my first impression is sounds like more work than its worth to me. :) I of course like the name in practice, but in reality, it makes things more challenging, which to say my time is already limitied, with helping out on a few projects now, gwt svg lib, gwtp and this. Hmmm

**Comment by twistedpair** [comment]
You're right. At the end of the day, as long as the code compiles and deploys, and Maven does its magic, what's in a name? I must admit, I'm a little obsessive compulsive on naming, but I also have jars from bouncycastle in my apps... so I can't complain.

**Comment by branflake2267** [comment]
Good point. I like that. :)

**Comment by branflake2267** [comment]
Wahoo, we got the go ahead with the naming (that is imperfect :)). well at least it will make it easier to implement via maven. :)

**Comment by twistedpair** [comment]
Do you want to try to get the v3.8.1 jars out there? Just note, they really, really don't like to revert them, so it's got to be done correctly the first time.

**Comment by branflake2267** [comment]
We can increment the version if we have changes. I guess are we set with the naming? What would be a consideration for change?

**Comment by twistedpair** [comment]
v3.9 is nearly in the can. Once I get the jars up on here, can you push the same tag build to Maven Central?

**Comment by branflake2267** [comment]
Are we going to change the name to what we are going to use for sonatype?

**Comment by twistedpair** [comment]
Good point. Can you add the issue? I can hop on it.

**Comment by branflake2267** [comment]
I updated this issue :)

**Comment by branflake2267** [comment]
I've renamed it in my latest branch and will be pulling shortly.

**Comment by twistedpair** [comment]
Let me know when you get that branch merged with the refactored namespaces. Otherwise my stuff will probably have 100% conflicts given the tree changes.

**Comment by branflake2267** [comment]
oh yea, I'll check now.

**Comment by branflake2267** [comment]
I'm going to quickly migrate the core to maven directory b/c I noticed I would have to setup the build path to get the tests running.

**Comment by branflake2267** [comment]
I've got the core directories moved to maven arch, now testing import. one more thing to tune in pom and then run tests.

**Comment by branflake2267** [comment]
Directions for setup to deploy to sonatype. 
http://www.sonatype.com/books/nexus-book/reference/staging-sect-deployment.html

**Comment by branflake2267** [comment]
This service is pretty cool. We moved GWTP to it. It builds all the pulls and marks if the pull passes. https://buildhive.cloudbees.com/job/ArcBees/

**Comment by branflake2267** [comment]
What do you think of using this to deploy? Christian moved GWTP over today and it works quite nice, but the free service doesn't allow for the settings.xml file to get uploaded, but the paid service has more features and does. I'm thinking of subscribing to the service for GWTP at the $15 a month but I wanted to see if your interesting in hosting building there too. 

http://www.cloudbees.com/platform/pricing/devcloud.cb

Whats your thoughts in having cloudbees do the build? @twistedpair

**Comment by twistedpair** [comment]
@branflake2267 
I checked out BuildHive and was pretty unimpressed. It was quite slow and very 1999 in design and presentation. It also failed to even successfully build and get through all the tests without being killed by their watchdog.

After using TeamCity, I find Jenkins to be quite clunky. However, CodeBetter has yet to get back to us.

How well does GWTP work for you on there? If you're looking @ $15 a month, how about getting an AWS account and just running this on a micro instance for free?

**Comment by branflake2267** [comment]
Hmm. bummer and seemed the free instance ran good, but thats killer if the production is slow, b/c they bill by the minute. I think you have a good point then, aws seems the most feesible.

**Comment by branflake2267** [comment]
Codebetter is running teamcity which is nice by the way, but uploading a settings.xml is not possible on 7.03, and is possible on 7.1, which could be done on aws. The settings would have the permissions for the sona deployment.

**Comment by twistedpair** [comment]
I'll spin up a micro instance on my business's account (RunPartner.com) and see how the build looks on it. That being said, this is beyond the scope of just getting stuff onto Maven Central, so perhaps we should move it to another Issue number.

As to uploading the `settings.xml`, I'm not too keen on that from a security perspective that you'd be placing the keys and credentials on a community server beyond our control. I'd gladly buy a long term micro instance for this on my dime as they are pretty cheap (~$8/mo) and I've got other things I could run on there.

**Comment by branflake2267** [comment]
I've been trying to find a nice cheap way to get GWTP deployed thats dependable, in the open which can deploy easily to sona nexus and funny this is falling about the same time too, so I've been thinking about both some. 

Cloudbees seems expensive when you look a the build minutes and it builds on each pull, but is nice to let you know the pull is a success, but Codebetter, which works great is 7.0.3 and is more difficult to setup the server permissions, and I think I would have to work up some credentials workaround for getting the snapshots and releases from it.  Teamcity 7.1 has the new features and looks even better and can use the settings.xml, and the reason I wanted to use it b/c I'd like to see it easy as local maven on my laptop. I guess I wasn't to concerned about security with the sona credentials, but you do have a point with that. 

I'm also willing to pay for an instance, and Christian also looking at spinning up an aws instance but there investigating it. I started to setup my server today, I've got a few in a rack at home, but I hate maintaining servers these days when you can host on the cheap in the cloud. 

I could pay for an instance too. Gonevertical advertising brings in about 50-80 a month from my docs and stuff floating around so I could purchase an instance to put teamcity 7.1 on. 

I guess at the end of the day I was hoping for something that didn't take any effort after it was setup and could deploy to sona once a new build comes in at least to the snapshot. And with no power, internet or labor issues to worry about :)

**Comment by rwl** [comment]
Once set up, deploying a snapshot to sonatype is simply:

```
$ mvn clean deploy
```

To stage a new release is:

```
$ mvn release:clean
$ mvn release:prepare
$ mvn release:perform
```

While nightly snapshots would be nice, just deploying the occasional snapshot may be sufficient.

**Comment by branflake2267** [comment]
Thanks for the release commands, thats something I'm not as proficient at yet. I'm familiar with getting snapshots out, but haven't done releases yet. :) Anyway, I'm thinking Joseph's done this more than I :)

**Comment by branflake2267** [comment]
The link on the readme isn't working for travis ci server, but its cool :)

**Comment by branflake2267** [comment]
I applied to teamcity.jetbrains.com which I see GWT is being built here to. 
http://www.jetbrains.com/eforms/openSourceRequest.action?licenseRequest=TCOSL5

**Comment by branflake2267** [comment]
I see your forking with org gwt-maps-api, I'm assuming you don't like the repo config?

**Comment by branflake2267** [comment]
I setup a teamcity server http://teamcity.gonevertical.org/

**Comment by branflake2267** [comment]
mvn test doesn't work yet, pom.xml has to be enhanced. tests run in junit runner fine.

**Comment by branflake2267** [comment]
I got the build server working http://teamcity.gonevertical.org/, sign up if you like and I'll add you to the project.

**Comment by branflake2267** [comment]
I added account to gonevertical-apis.appspot.com account so I didn't have to publish my main credentials in settings.xml for gae deploy via manen on build server.

**Comment by branflake2267** [comment]
maven gae deploy from ci server is ready. mvn clean deploy -DskipTests=true - deployed version 50 tonight. 

TODO: revisit separating junit/gwtunit tests

**Comment by branflake2267** [comment]
Snapsnot is deployed to nexus server. Its working.

**Comment by branflake2267** [comment]
Notified nexus ticket of upload. Waiting for ok, to release. I'll work on the tests again tomorrow.

**Comment by rwl** [comment]
In the interests of having a more professional looking groupId, I have created an organisation:

https://github.com/gwt-maps-api

I have added @branflake2267 and @twistedpair as owners and it should be straightforward to transfer the repo over.

**Comment by branflake2267** [comment]
I've noticed. I've been pondering that road and I'm not sure I want to go that direction. As much as it makes sense to me, its not about the naming for me and I think its about the quality and consistency of the library over the life of it. I don't use a library b/c of its name, I use it b/c of the features, quality, testing and such. And if it doesn't fit my needs, I fork and modify it and do whatever I like, and thats what this l library offers too. I appreciate the the thought, but I'm not sure I want to go down that road.

**Comment by branflake2267** [comment]
I'm working on the poms more, trying to get mvn integration-test to run the gwt tests and mvn test to skip the gwt tests. In prep so build goes 100% automatic for snap shot, and keeps ide testing easy.

**Comment by branflake2267** [comment]
Wahoo, I've got the pom.xml configured so it works. I've got a nice headache so I'll come back and do the formatting and some clean up and pull later, add it to the build server, and we should be good. It will deploy snapshot and to gae automatically. :)

**Comment by branflake2267** [comment]
I'll also come back and test auto import and setup in eclipse.

**Comment by branflake2267** [comment]
I'm testing 'mvn clean integration-test deploy' and the build server is now setup to deploy the snapshot and deploy showcase to gae automatically. I'll close this if I can get a successful set of events. :) Some tuning may be needed.

**Comment by branflake2267** [comment]
the build server is failing a few tests like:

``` java
[com.google.gwt.junit.tools.GWTTestSuite@1d10c424] com.google.gwt.maps.client.overlays.OverlayViewGwtTest.testDraw
[22:44:23][com.google.gwt.maps.client.overlays.OverlayViewGwtTest.testDraw] java.lang.RuntimeException: Remote test failed at 127.0.0.1 / Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.0.19) Gecko/2010031422 Firefox/3.0.19
[22:44:23]
[com.google.gwt.maps.client.overlays.OverlayViewGwtTest.testDraw] java.lang.RuntimeException: Remote test failed at 127.0.0.1 / Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.0.19) Gecko/2010031422 Firefox/3.0.19
    at com.google.gwt.junit.JUnitShell.processTestResult(JUnitShell.java:1283)
    at com.google.gwt.junit.JUnitShell.runTestImpl(JUnitShell.java:1403)
    at com.google.gwt.junit.JUnitShell.runTestImpl(JUnitShell.java:1304)
    at com.google.gwt.junit.JUnitShell.runTest(JUnitShell.java:652)
    at com.google.gwt.junit.client.GWTTestCase.runTest(GWTTestCase.java:441)
    at junit.framework.TestCase.runBare(TestCase.java:134)
    at junit.framework.TestResult$1.protect(TestResult.java:110)
    at junit.framework.TestResult.runProtected(TestResult.java:128)
    at junit.framework.TestResult.run(TestResult.java:113)
    at junit.framework.TestCase.run(TestCase.java:124)
    at com.google.gwt.junit.client.GWTTestCase.run(GWTTestCase.java:296)
    at junit.framework.TestSuite.runTest(TestSuite.java:232)
    at junit.framework.TestSuite.run(TestSuite.java:227)
    at junit.framework.TestSuite.runTest(TestSuite.java:232)
    at junit.framework.TestSuite.run(TestSuite.java:227)
    at junit.framework.TestSuite.runTest(TestSuite.java:232)
    at junit.framework.TestSuite.run(TestSuite.java:227)
    at org.codehaus.mojo.gwt.test.MavenTestRunner.doRun(MavenTestRunner.java:105)
    at junit.textui.TestRunner.start(TestRunner.java:180)
    at org.codehaus.mojo.gwt.test.MavenTestRunner.main(MavenTestRunner.java:63)
Caused by: java.lang.Exception: com.google.gwt.core.client.JavaScriptException: (null) @com.google.gwt.maps.client.overlays.OverlayView::draw()([]): null
    at com.google.gwt.dev.shell.BrowserChannelServer.invokeJavascript(BrowserChannelServer.java:249)
    at com.google.gwt.dev.shell.ModuleSpaceOOPHM.doInvoke(ModuleSpaceOOPHM.java:136)
    at com.google.gwt.dev.shell.ModuleSpace.invokeNative(ModuleSpace.java:571)
    at com.google.gwt.dev.shell.ModuleSpace.invokeNativeVoid(ModuleSpace.java:299)
    at com.google.gwt.dev.shell.JavaScriptHost.invokeNativeVoid(JavaScriptHost.java:107)
    at com.google.gwt.maps.client.overlays.OverlayView$.draw$(OverlayView.java)
    at com.google.gwt.maps.client.overlays.OverlayViewGwtTest$2.run(OverlayViewGwtTest.java:59)
    at com.google.gwt.ajaxloader.client.ExceptionHelper.runProtected(ExceptionHelper.java:36)
    at sun.reflect.GeneratedMethodAccessor48.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:616)
    at com.google.gwt.dev.shell.MethodAdaptor.invoke(MethodAdaptor.java:103)
    at com.google.gwt.dev.shell.MethodDispatch.invoke(MethodDispatch.java:71)
    at com.google.gwt.dev.shell.OophmSessionHandler.invoke(OophmSessionHandler.java:172)
    at com.google.gwt.dev.shell.BrowserChannelServer.reactToMessages(BrowserChannelServer.java:293)
    at com.google.gwt.dev.shell.BrowserChannelServer.processConnection(BrowserChannelServer.java:547)
    at com.google.gwt.dev.shell.BrowserChannelServer.run(BrowserChannelServer.java:364)
    at java.lang.Thread.run(Thread.java:679)
```

**Comment by branflake2267** [comment]
~20 tests are failing, will have to revisit this on another day, but the build server is trying to build it, got everything running.

**Comment by branflake2267** [comment]
Some things yet to do, signing. I'm working on the signing for gwtp, so I'll copy theres once I get the release finished too.

Staging ruleset evaluation on repository 'com.github.branflake2267-065 (u:branflake2267, a:24.113.1.67)' has failed.

Staging Sources Validation
    -Missing: no sources jar found in folder '/com/github/branflake2267/gwt-maps-api/3.9.0'

Staging Signature Validation
    -Missing Signature: '/com/github/branflake2267/gwt-maps/3.9.0/gwt-maps-3.9.0.pom.asc' does not exist for 'gwt-maps-3.9.0.pom'.
    -Missing Signature: '/com/github/branflake2267/gwt-maps-showcase/3.9.0/gwt-maps-showcase-3.9.0.pom.asc' does not exist for 'gwt-maps-showcase-3.9.0.pom'.
    -Missing Signature: '/com/github/branflake2267/gwt-maps-showcase/3.9.0/gwt-maps-showcase-3.9.0.war.asc' does not exist for 'gwt-maps-showcase-3.9.0.war'.
    -Missing Signature: '/com/github/branflake2267/gwt-maps-api/3.9.0/gwt-maps-api-3.9.0.jar.asc' does not exist for 'gwt-maps-api-3.9.0.jar'.
    -Missing Signature: '/com/github/branflake2267/gwt-maps-api/3.9.0/gwt-maps-api-3.9.0-javadoc.jar.asc' does not exist for 'gwt-maps-api-3.9.0-javadoc.jar'.
    -Missing Signature: '/com/github/branflake2267/gwt-maps-api/3.9.0/gwt-maps-api-3.9.0.pom.asc' does not exist for 'gwt-maps-api-3.9.0.pom'.

**Comment by thetaquarii** [comment]
Hi,

Can I get the lib from Maven repo now? Which version and in which repo?
Thanks in advance!

**Comment by branflake2267** [comment]
Both the snap shot and release are available. The notes for adding are here: https://github.com/branflake2267/GWT-Maps-V3-Api

**Comment by thetaquarii** [comment]
Thanks! Keep up the good work!

BTW, I guess `2. Add the inherits statement to your module.gwt.xml.` has to be updated from "<inherits name='com.google.gwt.maps.Apis_Google_Maps' />" to "<inherits name='com.google.gwt.maps.Maps' />".

**Comment by branflake2267** [comment]
Thanks, my bad. https://github.com/branflake2267/GWT-Maps-V3-Api/blob/master/gwt-maps-showcase/src/main/java/com/google/gwt/maps/testing/Showcase.gwt.xml

``` xml
<inherits name='com.google.gwt.maps.Maps' />
```
