### ISSUE TITLE
Page scrolled while map mouse zooming enabled

### ISSUE THREAD

**Issue by wikiro** [branflake2267/GWT-Maps-V3-Api#124]
Firefox 10.0.1 win 7 x64

Bug: enable map mouse wheel zooming = true
open FF, zooming map - page scrolling down or up too

Here is [the fix code](http://code.google.com/p/gmaps-api-issues/issues/detail?id=3652#c14) in javascript

**Comment by branflake2267** [comment]
Thanks for reporting. I'll get this done asap. :)

**Comment by branflake2267** [comment]
Thanks for linking me to the workaround!

**Comment by branflake2267** [comment]
This looks like an api bug and I'm not sure exactly what you are referring to with zooming = true. Would it be possible to cherry pick the code for me?

**Comment by twistedpair** [comment]
This is fixed in FF. I just tested in FF 18. Is there a reason you're using 8 versions back in FF? Perhaps because that was an ESR version?

**Comment by wikiro** [comment]
can you check this in last opera? if I fast zooming error occurs. 
yes, in FF 18 it is fixed
