### ISSUE TITLE
Add OpenStreetMaps Layer

### ISSUE THREAD

**Issue by wikiro** [branflake2267/GWT-Maps-V3-Api#125]
New feature. Can you add osm layer by calling method? 
## Like this code:

``` java
MapOptions options = MapOptions.newInstance();
        options.setZoom(zoom);
        options.setCenter(LatLng.newInstance(lat, lon));
        options.setMapTypeId(MapTypeId.OSM);
        mapWidget = new MapWidget(options);
        mapWidget.addStyleName("map");
        add(mapWidget);
```
## In version google maps api 2 it was:

``` java
map.addMapType(CommonMapTypes.getOsmMap(minZoom, maxZoom));

public static MapType getOsmMap(Integer minimumZoom, Integer maximumZoom) {
        CopyrightCollection copyrightCollection = new CopyrightCollection("<a href=\"http://www.openstreetmap.org/\">OpenStreetMap</a>");
        copyrightCollection.addCopyright(new Copyright(1, LatLngBounds.newInstance(LatLng.newInstance(-90, -180), LatLng.newInstance(90, 180)), 0, " "));
        TileLayer mapnikTileLayer = new TileLayer(copyrightCollection, minimumZoom, maximumZoom){
            public double getOpacity() { return 1.0; }
            public String getTileURL(Point tile, int zoomLevel) { return "http://tile.openstreetmap.org/" + zoomLevel + "/" + tile.getX() + "/" + tile.getY() + ".png";}
            public boolean isPng() { return true;}
        };
        MapType osm = new MapType(new TileLayer[]{mapnikTileLayer}, MapType.getNormalMap().getProjection(), "OSM");
        return osm;
    }
```

**Comment by branflake2267** [comment]
I would think so. Thanks for reporting. I'll aim for looking at this more this weekend.

**Comment by branflake2267** [comment]
If you need it sooner, feel free to fork, modify and pull against the master. :)

**Comment by twistedpair** [comment]
Here is [the example](http://wiki.openstreetmap.org/wiki/Google_Maps_Example) in the pure Google Maps V3 API to achieve this:

``` javascript
            var element = document.getElementById("map");

            /*
            Build list of map types.
            You can also use var mapTypeIds = ["roadmap", "satellite", "hybrid", "terrain", "OSM"]
            but static lists sucks when google updates the default list of map types.
            */
            var mapTypeIds = [];
            for(var type in google.maps.MapTypeId) {
                mapTypeIds.push(google.maps.MapTypeId[type]);
            }
            mapTypeIds.push("OSM");

            var map = new google.maps.Map(element, {
                center: new google.maps.LatLng(48.1391265, 11.580186300000037),
                zoom: 11,
                mapTypeId: "OSM",
                mapTypeControlOptions: {
                    mapTypeIds: mapTypeIds
                }
            });

            map.mapTypes.set("OSM", new google.maps.ImageMapType({
                getTileUrl: function(coord, zoom) {
                    return "http://tile.openstreetmap.org/" + zoom + "/" + coord.x + "/" + coord.y + ".png";
                },
                tileSize: new google.maps.Size(256, 256),
                name: "OpenStreetMap",
                maxZoom: 18
            }));
```

So there should not be a need for a core library change as it can be implemented from the GWT GMaps API. Of course a reference implementation would be a help to folks.

**Comment by wikiro** [comment]
Please create method

MapWidget map....
map.enableOSM();
map.setMapTypeId(MapTypeId.OSM)

**Comment by branflake2267** [comment]
Now that I look I don't see OSM as an option in the v3. Do you know if that OSM still exists?
https://developers.google.com/maps/documentation/javascript/reference#MapTypeId

**Comment by twistedpair** [comment]
@branflake2267 from the looks of the code sample, it is a custom type (tile layer) being defined by the example.

**Comment by branflake2267** [comment]
Ah, thanks @twistedpair.

**Comment by wikiro** [comment]
**Here the working code!** please use it to create usefull function like map.enableOSm(); map.setMapTypeId(MapTypeId.OSM)  

``` java
public CommonMap(double lat, double lon, int zoom, int mapTypeId) {
        MapTypeControlOptions controlOptions = MapTypeControlOptions.newInstance();
        controlOptions.setMapTypeIds(new String[] { "OSM", MapTypeId.ROADMAP.toString(), MapTypeId.HYBRID.toString(), MapTypeId.SATELLITE.toString(), MapTypeId.TERRAIN.toString()});

        setStyleName("commonMap");
        MapOptions options = MapOptions.newInstance();
        options.setZoom(zoom);
        options.setCenter(LatLng.newInstance(lat, lon));
        options.setMapTypeControlOptions(controlOptions);
        options.setScrollWheel(true);
        options.setMapTypeControl(true);

        ImageMapType osmMapType = getOsmMapType();
        mapWidget = new MapWidget(options);
        mapWidget.addStyleName("map");
        mapWidget.getMapTypeRegistry().set("OSM", osmMapType);
        add(mapWidget);

        if (mapTypeId == 2) {
            mapWidget.setMapTypeId("OSM");
        } else {
            mapWidget.setMapTypeId(MapTypeId.ROADMAP.toString());
        }
        addMousePositionFetching();
    }

    private ImageMapType getOsmMapType() {
        ImageMapTypeOptions opts = ImageMapTypeOptions.newInstance();
        opts.setMaxZoom(20);
        opts.setMinZoom(1);
        opts.setName("OSM");
        opts.setTileSize(Size.newInstance(256, 256));
        opts.setTileUrl(new TileUrlCallBack() {
            public String getTileUrl(Point point, int zoom) {
                return "http://tile.openstreetmap.org/" + zoom + "/" + ((int) point.getX()) + "/" + ((int) point.getY()) + ".png";
            }
        });

        return ImageMapType.newInstance(opts);
    }
```

**Comment by branflake2267** [comment]
If it works I'll add it. :) Our base line is the API reference and I haven't seen this, but that doesn't mean I won't add it. I'll aim to try it out soon. I'm behind this week, b/c I got the flu and I'm job hunting, but I intend to do some work late this weekend.

Thanks for providing the example that will help out. It seems the Street Maps API has been separated into its own class, b/c I created a simple street map example. So I'm wondering if this hasn't been refactored into something else with in Google's API. Nevertheless I'll investigate.

**Comment by branflake2267** [comment]
What you provided me reminds me of this example we made here:
https://github.com/branflake2267/GWT-Maps-V3-Api/blob/master/gwt-maps-showcase/src/main/java/com/google/gwt/maps/testing/client/maps/StreetViewCustomMapWidget.java

**Comment by twistedpair** [comment]
@branflake2267 at the very least there can be a showcase example of using OSM that folks can use as their reference implementation of OSM in the library.

**Comment by twistedpair** [comment]
Closed as this example should be sufficient for uses. I had thought however that we could add an `extras` package, or separate jar (i.e. `gwt-maps-api-extras`). This way you can implement the raw GMaps API, or use extra functionality/widgets too. It would provide a clear separation and maintainability between the _official API_ and supplemental feature requests.

**Comment by branflake2267** [comment]
Nice work! I'll aim to do more this weekend and release what we've worked on. I also provide my release notes so you can do it as well. :)

Sounds interesting. I'm not sure I see what would qualify as going into extras yet? But you have a point if it is extra and an update comes down. The other thought that comes to mind, is do we want to create and extra b/c that means another item to maintain. :)

**Comment by twistedpair** [comment]
Very true. For now, I would say it is not a high priority. I know folks have "nice to have" methods and features, but support/maintenance is the killer in software. However, should compelling "extra" requests come in, and we have extra cycles, it could be useful for implementers to contribute to (i.e. if they have a neat widget from their maps app).

**Comment by branflake2267** [comment]
Good points :) Yeah, extra cycles..., another good point. That should happen after these bugs get killed and I'd like to try to start work on 3.10 features.
