### ISSUE TITLE
Unable to recreate a MapWidget

### ISSUE THREAD

**Issue by sonytricoire** [branflake2267/GWT-Maps-V3-Api#127]
Since API 3.9.0-build-17 (and also 3.10.0-alpha-1)

If I want to recreate an mapWidget the tiles are not loaded on the whole widget size.

Example with showcase by replacing existing drawOverlayViewMap with the following one (the aim is only to add a button to clear the widget and to add a new one) :

``` java
// existing method
private void drawOverlayViewMap() {

        OverlayViewMapWidget wMap = new OverlayViewMapWidget();
        addMapWidget(wMap);

        // This is just ot show the effect of behind the scenes
        Button resetBtn = new Button("Reset");
        resetBtn.addClickHandler(new ClickHandler() {
            public void onClick(ClickEvent event) {
                RootPanel.get(mapsContainer).clear();

                OverlayViewMapWidget wMap2 = new OverlayViewMapWidget();
                addMapWidget(wMap2);
            }
        });

        RootPanel.get().add(resetBtn);
    }
```

In this case, first draw is ok but after clicking on the reset button, only the top-left tile is displayed.

**Comment by branflake2267** [comment]
Could you try

``` java
wmap.triggerResize()
```

**Comment by sonytricoire** [comment]
Calling triggerResize() does not fix the problem.

**Comment by sonytricoire** [comment]
However, I found a workaround by keeping a reference to the initialized
mapWidget and then adding it to a cleared container.

**Comment by branflake2267** [comment]
Thanks for reporting. Good job on workaround. Do you think the above code is enough for me to easily and quickly replicate the problem? If not, could you provide a more complete sample in which I could replicate the issue?

Does this only happen in debug mode? Are you using Firefox or Chrome to debug?

**Comment by sonytricoire** [comment]
Yes, with the code in the issue, a simple method replace from actual
showcase code will show you the problem.

I got the problem in debug mode and I did not tried to get it in production
mode. I used Chrome.

**Comment by branflake2267** [comment]
Could you try Firefox and see if there is a difference?

**Comment by branflake2267** [comment]
I have a feeling its related to the _gwt_Object

**Comment by sonytricoire** [comment]
Yes same problem with Firefox.

**Comment by branflake2267** [comment]
Thanks :)

**Comment by branflake2267** [comment]
I've replicated it :)

**Comment by branflake2267** [comment]
using .triggerResize() on the second map fixes the problem. Create and call a method on the class that creates the map that uses wmap.triggerResize() works.

**Comment by branflake2267** [comment]
What I did...

``` java
    Button resetBtn = new Button("Reset");
    resetBtn.addClickHandler(new ClickHandler() {
        public void onClick(ClickEvent event) {
            wMap.clear();

            OverlayViewMapWidget wMap2 = new OverlayViewMapWidget();
            addMapWidget(wMap2);
            wMap2.resize();
        }
    });
```
