### ISSUE TITLE
Typo in StreetViewService

### ISSUE THREAD

**Issue by tvernum** [branflake2267/GWT-Maps-V3-Api#128]
In StreetViewService the _getInstance_ method is incorrectly spelt `newInstnace`

**Comment by branflake2267** [comment]
Good find. Thanks for reporting.

**Comment by twistedpair** [comment]
Arr, if only JSNI supported an interface being used by more than a single JSO, contracts could prevent any such typo.

**Comment by branflake2267** [comment]
Good point. I suppose I could have used eclipse check style, it has a nice regex setup.
