### ISSUE TITLE
OverlayView.onRemove() argument methods cannot be used

### ISSUE THREAD

**Issue by sonytricoire** [branflake2267/GWT-Maps-V3-Api#131]
Using methods.getPanes().getFloatPane() works fine in onAdd and onDraw, but it does not in the onRemove method.

**Comment by branflake2267** [comment]
Thanks for reporting. I wonder if that is not available in that method. Do you know if it should work?

**Comment by sonytricoire** [comment]
I don't really know but I think this cause a big problem for me : I'm
unable to remove a CustomOverlay (i.e. a class implementing OverlayView
methods) from a map widget.

I tried to remove a overlayview object by calling setMap(null) and also
trying to invoke clear() on this overlay view.
I also tried to call removeFromParent() in the onRemove() method.

If you use the OverlayView sample in showcase project and try to put the
htmlOverlayMessage inside the map (I think is a bug to add it in the panel
at the top) you'll see that you cannot remove it from the map.

**Comment by branflake2267** [comment]
Ok. I should have made a more complete example to test more. :) Do you think you could provide a simple example which I could test that failure? I can see if something is missing or broken...

**Comment by sonytricoire** [comment]
Yep I can do it on Monday..

**Comment by branflake2267** [comment]
Thank you :)

**Comment by sonytricoire** [comment]
Hi Brandon,

I just sent a pull request with patched overlayview demo.

Hope it's a good way for you to review.

**Comment by branflake2267** [comment]
That is perfect! Thanks so much for adding more to the sample. That will allow me to test it more. Awesome!

**Comment by branflake2267** [comment]
I'm going to say this is expected onRemove. I made a note. Please re-open if you think this should work. 

Thanks for adding to the example.

**Comment by branflake2267** [comment]
https://github.com/branflake2267/GWT-Maps-V3-Api/pull/149
