### ISSUE TITLE
Polyline object - new event when vertex was moved

### ISSUE THREAD

**Issue by wikiro** [branflake2267/GWT-Maps-V3-Api#132]
Polyline - there is no event like `addPolylineLineUpdatedHandler` (when vertex was moved to some place while editing)

please, create it!

**Comment by branflake2267** [comment]
Thanks for reporting. :)

**Comment by wikiro** [comment]
I'm workarounding this feature. If i move a vertex - event set is fired! if i add new vertex while editing between 2 vertex by draging circle - event insert is fired. so this feature is not need.
