### ISSUE TITLE
Add removal future version number to deprecated methods

### ISSUE THREAD

**Issue by twistedpair** [branflake2267/GWT-Maps-V3-Api#138]
Add deprecation  version numbers to the currently deprecated methods for more formal end of support. Since the next release of note is 3.10, currently deprecated methods will be removed in 3.11 giving api consumers a full release cycle to update their implementations.

**Comment by branflake2267** [comment]
How would that look?

**Comment by twistedpair** [comment]
Just numbers in the comments of the deprecated method. 
i.e. @deprecated ... "method deprecated, see proper_method(). This method will be removed in release 3.11"

**Comment by branflake2267** [comment]
Ok, gotcha. I wanted to double check to see if something special was in mind. :)

**Comment by twistedpair** [comment]
Done.
