### ISSUE TITLE
No ployline displayed

### ISSUE THREAD

**Issue by bhamid** [branflake2267/GWT-Maps-V3-Api#14]
problem with PolyLine
Hello;
I want to display a polyline on my map google by giving a list of points (JsArray points).
the polyline is not displayed, here is my code:

LatLng[] a = new LatLng[3];
a[0] = LatLng.newInstance(2.956377, 36.77403);
a[1] = LatLng.newInstance(2.95372, 37);
a[2] = LatLng.newInstance(2.97, 36.78403);
JsArray<LatLng> listLatLng = ArrayHelper.toJsArray(a);
options.setMap(mapWidget);
options.setPath(listLatLng);
options.setStrokeColor("#FF0000");//couleur du tracé
options.setStrokeOpacity(1.0);//opacité du tracé
options.setStrokeWeight(2);//grosseur du tracé
Polyline polyLine = Polyline.newInstance(options);

help me please!

**Comment by twistedpair** [comment]
Your code worked fine for me. Perhaps you were not zoomed into the proper region to see the Polyline on the map?

You still raise a good point. I added a Polyline example to the project that shows how to draw three different Polylines on the map, and gives an example function to set the map to the center of a given Polyline. Check out the most recent revision from GitHub. The example is not yet up on AppSpot, but should be in a day or two.

**Comment by twistedpair** [comment]
Updated the online showcase with three examples of polylines, including a large polyline data example. 

[See Showcase](gonevertical-apis.appspot.com)
