### ISSUE TITLE
Prune merged branches

### ISSUE THREAD

**Issue by twistedpair** [branflake2267/GWT-Maps-V3-Api#140]
I already removed my joe_v3.9.0 branch.

@branflake2267 Can you remove your merged [brandon_release](https://github.com/branflake2267/GWT-Maps-V3-Api/tree/brandon_release) branch? I assume it is no longer needed, but wanted to let you do that in case you're still using it locally.

**Comment by branflake2267** [comment]
Yeah, I pruned a few the other day. :) I'll remove it.

**Comment by branflake2267** [comment]
I like to reuse the brandon_release when I release. B/c the maven plugin will increment the pom's and then I push once its done.

**Comment by branflake2267** [comment]
I'll delete it on remote. :)

**Comment by twistedpair** [comment]
Sounds good :+1:
