### ISSUE TITLE
Community link broken on home page

### ISSUE THREAD

**Issue by branflake2267** [branflake2267/GWT-Maps-V3-Api#144]
Community link broken on homepage.

**Comment by branflake2267** [comment]
I'll come back to this if someone doesn't beat me to it, after work...

**Comment by twistedpair** [comment]
Ha, if only such things were not blocked by nearly every corp these days.

**Comment by branflake2267** [comment]
Well, I manually blocking it. :) b/c github lists the things I work on :) and I want to be honest too.

**Comment by branflake2267** [comment]
lol :)
