### ISSUE TITLE
HouseCleaning: MapEvent type declarations

### ISSUE THREAD

**Issue by twistedpair** [branflake2267/GWT-Maps-V3-Api#15]
Noticed that we have a number of Eclipse warnings about the MapEvent type. We need to properly parameterize these. However, I noticed in looking at this that in the below code, we can see that addHandlerImpl() takes a MapHander that extends MapEvent, but MapEvent extends MapHandler. Seems a bit cyclical. We should clean this up.
# MapEvent

``` java
/**
 * Inherit this into unique Map Event
 *
 * @param <H> {@link MapHandler}
 * @param <E> {@link MapEvent}
 */
public abstract class MapEvent<H extends MapHandler<E>, E> extends GwtEvent<H> {
```
# MapHandlerRegistration

``` java
/**
   * process the callback and send it to the handler
   * @param jso
   * @param eventName
   * @param handler
   * @param formatter
   */
  private static native <E extends MapEvent> JavaScriptObject addHandlerImpl(
      JavaScriptObject jso,
      String eventName, 
      MapHandler<E> handler, 
      MapEventFormatter<E> formatter) /*-{
    var callback = function(event) { 
      @com.google.gwt.maps.client.events.MapHandlerRegistration::onCallback(Lcom/google/gwt/maps/client/events/MapHandler;Lcom/google/gwt/ajaxloader/client/Properties;Lcom/google/gwt/maps/client/events/MapEventFormatter;)(handler, event, formatter);
    };          
    return $wnd.google.maps.event.addListener(jso, eventName, callback)
  }-*/;
```

**Comment by branflake2267** [comment]
Sounds good. :)

**Comment by branflake2267** [comment]
Have you done anything with this?

**Comment by branflake2267** [comment]
Hmmm, I'm looking at the handlers, and I remember trying to paramertize the MapEvent before but seemed a static type was slowing me down. I haven't found it all yet. While I'm looking I see line width of 80, do you mind if I reset the stuff to 120?

**Comment by branflake2267** [comment]
Wow, flash backs trying to extract this. Ugh b/c the TYPE is static it causes some inheritance, then GwtEvent MapEvent wants both the event type and handler creates some fun. :)

**Comment by branflake2267** [comment]
How far down the rabbit hole would you like to go on this? I think b/c of the way GwtEvent I was a little constrained and  I also generified it a bit. Since this works, I'm not sure its worth it. Thoughts?

Although adding a wild card gets rid of the eclipse warning. 

``` java
 public static <E extends MapEvent<?, E>> HandlerRegistration addHandler(...
```

**Comment by twistedpair** [comment]
Frankly it is not a big deal. Thanks for looking into it. I just try not to have any warnings in Eclipse and this is one of the few we have left. Frankly, given the limitations of the GWT JSO design and the Maps API, I concede that it is permissible to just suppress this warning, given that we've both investigated and vetted it.

**Comment by branflake2267** [comment]
Sounds good. :)

**Comment by branflake2267** [comment]
I'm going to close my branch pull request on this issue for now. And leave as is. :)
