### ISSUE TITLE
PolylineOptions doesn't have setIcons method

### ISSUE THREAD

**Issue by riparrag** [branflake2267/GWT-Maps-V3-Api#153]
PolylineOptions not includes setIcons.

Also not included IconSequence, Symbol and SymbolPath.

**Comment by branflake2267** [comment]
Thanks for reporting. If someone else doesn't beat me to it, I'll aim to work on this saturday.

**Comment by irvjc82** [comment]
Same problem here!

**Comment by aivaldi** [comment]
Also I need it, and it is not included in the 3.10 alpha version.

**Comment by branflake2267** [comment]
I'll add it asap, after work or on the weekend, unless someone beats me to it. Then I can build and release it :)

**Comment by twistedpair** [comment]
See the existing tracking story for this #59

**Comment by branflake2267** [comment]
Oops, I should have stated that in my comments, the 3.10 stuff hasn't been finished yet.

**Comment by twistedpair** [comment]
@branflake2267  3.10 milestone is overshot. What do you think is a new goal for it? How much is left to knock off?
