### ISSUE TITLE
Wrong signature method: MapImpl.getControls()

### ISSUE THREAD

**Issue by idegregorio** [branflake2267/GWT-Maps-V3-Api#163]
The method `MapImpl.getControls()` has the wrong signature. It currently returns a `MVCArray<Element>` but the native javascript method returns a `Array.<MVCArray.<Node>>` (not clear to me what that translates into java).

**Comment by branflake2267** [comment]
Thanks for reporting.

**Comment by branflake2267** [comment]
I'll have to investigate whether this was intended or not. The MVCArray is wrapping an MVCArray, so I'll have to double check. 

https://github.com/branflake2267/GWT-Maps-V3-Api/blob/master/gwt-maps-api/src/main/java/com/google/gwt/maps/client/mvc/MVCArray.java

**Comment by branflake2267** [comment]
Interesting, I don't see the js api reference anymore Map.getControls() : https://developers.google.com/maps/documentation/javascript/reference#Map

**Comment by idegregorio** [comment]
It's under Properties of google.maps.Map class,

By the way, I've been adding custom overlays to the map and found that I
couldn't hook mouse events on them with your MapHandlerRegistration. My
custom overlays are just plain <div> elements stuck on the map together
with an OverlayView property that allows them to handle the onDraw,
onRemove and onAdd events.

I would try things like:

MapHandlerRegistration.addDomListener(div.getElement(),
ClickEvent.getType(), new ClickMapHandler(){ public void
onEvent(ClickMapEvent event){} }, false);

to no result (i.e., onEvent(ClickMapEvent event) would never be invoked).
After some debugging, I found that if I passed an ClickEventFormatter to
the addDomListener then my ClickMapHandler would work. I created a small
MapHandlerRegistration utility class (attached) to give myself access to
the native methods. As you can see, I simply copied the three relevant
methods from your class and make some minor modifications.

I don't report this as a bug because I don't really know if it was due to
my poor understanding of how to use your MapHandlerRegistration class.

Kind regards,
Ignacio de Gregorio.

**Comment by branflake2267** [comment]
Ah, there it is. Hmm, I'll see if I did that array<mvcarray> correctly. 

The next topic, well its not a bug, but could be a feature add. Nevertheless, I can direct you on options. GWT shadows the dom the and creates a parallel event structure it adds a little complexity. But I'll explain my work around if you can create a new issue :)

**Comment by superbalou** [comment]
Hello, 

I don't manage to handle mouse events on div elements added to my custom overlay. 

I added the div elements to the "Overlay Mouse Target" but nothing happens when I click on it, no matter what I use to handle the event (GWT addDomHandler or MapHandlerRegistration)

Do you have an idea ?

**Comment by superbalou** [comment]
Oops, I got it working using sinkEvents on my div element. 

Is it the only way ?

**Comment by schweighart** [comment]
There is an other crazy solution. Create your divs outside of the map and then add this element to the map.

**Comment by superbalou** [comment]
I think I'm gonna go for yours because it allows me to dissociate mouse events from the map and those from the overlaying div more easily. 

Thanks.

**Comment by twistedpair** [comment]
Generally, with GWT, directing calling the sinkEvents methods are the surest bet.
