### ISSUE TITLE
PolylineOptions refers to wrong javadoc

### ISSUE THREAD

**Issue by riparrag** [branflake2267/GWT-Maps-V3-Api#164]
PolylineOptions is referencing to PolygonOptions javadoc

com.google.gwt.maps.client.overlays.PolylineOptions refers to: 
"https://developers.google.com/maps/documentation/javascript/reference#PolygonOptions"

**Comment by branflake2267** [comment]
Thanks for the find.

**Comment by twistedpair** [comment]
Three cheers for folks reading the docs! I made that error, my apologies.

**Comment by riparrag** [comment]
:)
Do you know when will be setIcons available ?

**Comment by branflake2267** [comment]
https://github.com/branflake2267/GWT-Maps-V3-Api/issues/59 - I've started on a couple but got bogged down with new job stuff. I'm aiming to do some work this weekend on this. :) Could fork, modify and pull, if we are taking to long :)

**Comment by twistedpair** [comment]
I'll try the icons on for size tonight too. :+1:

**Comment by branflake2267** [comment]
I'm switching gears at 3pm. I'm going to switch into maps. I'm going to test out the pom changes I made.

**Comment by twistedpair** [comment]
Ha. PST. Nothing like horizontal wind driven rain out here in Boston. :)

**Comment by branflake2267** [comment]
Funny :)
