### ISSUE TITLE
Add updates from Maps V3.9 API Release

### ISSUE THREAD

**Issue by twistedpair** [branflake2267/GWT-Maps-V3-Api#17]
There were very few changes, but we should confirm that they are all in there and updated our version numbers/docs.

> 3.9 15 May, 2012
> 
> Added:
> 
> Country restriction for Autocomplete (AutocompleteOptions.componentRestrictions) ( Issue 3899 )
> Regions and Cities type filters

See the official API [change log](http://code.google.com/p/gmaps-api-issues/wiki/JavascriptMapsAPIv3Changelog).

**Comment by twistedpair** [comment]
Reading through the change log, we need to confirm the following have been added too as these were since the initial code creation in December 2011 (strike through indicated feature completion or rejection):
- ~~orderBy, limit and offset for FusionTablesLayer~~
- ~~[DemographicsLayer](https://developers.google.com/maps/documentation/business/demographics)~~ (out of scope, commerical API only)
- ~~WeatherLayer~~
- ~~CloudLayer~~
- ~~HeatMapsLayer~~
- ~~TransitLayer~~
- ~~opacity to GroundOverlay~~
- ~~utc_offset and opening_hours to PlaceResult~~
- ~~clickToGo option to StreetViewPanoramaOptions~~
- ~~Click-to-go/Click-to-zoom in Street View~~
- ~~google.maps.geometry.poly.containsLocation()~~
- ~~google.maps.geometry.poly.isLocationOnEdge()~~
- ~~setOpacity() for ImageMapType~~
- ~~setOpacity() for GroundOverlay~~
- ~~"tilesLoaded" event for ImageMapType~~
- ~~stop() to MouseEvent, which stops event propagation~~
- ~~Added "visible" property for polys~~
- ~~Added imageDateControl to StreetViewPanorama~~
- ~~Add KmlLayer "status" property~~

**Comment by twistedpair** [comment]
HeatMapsLayer, TransitLayer, WeatherLayer now in the v3.9 branch.

**Comment by branflake2267** [comment]
Looks great!

**Comment by branflake2267** [comment]
Do you have plans to merge this branch into master?

**Comment by twistedpair** [comment]
Sure do. Mainly need to get the other big items in like the weather overlay with temperatures and the new custom polyline decorators (and demos). The other small things in the list should take only a few minutes each to update and test. I'll merge when done.

**Comment by branflake2267** [comment]
Let me know if you would like me to help put together something :)

**Comment by twistedpair** [comment]
Probably this weekend. Been pretty busy since vacation the other week, but getting back in the groove now. Nice job on all the work you've been kicking out!

**Comment by branflake2267** [comment]
Thanks. You too. Not a problem.. :)

**Comment by branflake2267** [comment]
Would you like me to catch this up and push it to master? Does more need to be done?

**Comment by branflake2267** [comment]
Have you been keeping up the list? Which should I take, I'm open to working on this tomorrow. Good job.

**Comment by twistedpair** [comment]
The list is up to date with my efforts. I've put my name on the last four, I plan to complete tonight. Mark the ones you've completed or will work on.

**Comment by branflake2267** [comment]
I marked off mine, place result or utc_offset. :)

I can aim to do the streeview next weekend, that is if I can sneak in some time between family time. I've promised my wife some family time :)

**Comment by twistedpair** [comment]
Completed all the features for v3.9.0 including some neat examples that flushed out a bug with ImageMapType.

**Comment by twistedpair** [comment]
Four broken tests. Resolve these and it is closed. Current is up to date with master.

**Comment by branflake2267** [comment]
Wahoo, I'm impressed :) I'll aim to get on that soon.

**Comment by twistedpair** [comment]
Fixed.

**Comment by tj-recess** [comment]
Has this been released?
I'm using 3.10.0-alpha-7 (from maven) and can't use Autocomplete component restrictions (similar to http://stackoverflow.com/a/10170421/877856). Please suggest.
