### ISSUE TITLE
When creating two maps on demand, the second map will be broken

### ISSUE THREAD

**Issue by mgmmmm** [branflake2267/GWT-Maps-V3-Api#172]
Hi!

I am trying to create two map objects on demand (and on the same page). The first map works fine, however the second map will be broken:
- it will use different options (from what I used in the map construction) 
- the active / tiled area will be offset from the view area.

If these maps are created one after the other from code, they will work fine. 
I am using the maps api version 3.10.0 alpha 2 with eclipse gwt setup.

I hope this is the right place to raise this issue. Thanks, 
Gabor

Here is a sample code with the problem:

``` java
public class MapsBugSample implements EntryPoint {
    private VerticalPanel vPanel;
    private int mapCount = 0;

    @Override
      public void onModuleLoad() {
        loadMapApi();
      }

      private void loadMapApi() {
        boolean sensor = true;

        // load all the libs for use in the maps
        ArrayList<LoadLibrary> loadLibraries = new ArrayList<LoadApi.LoadLibrary>();
        loadLibraries.add(LoadLibrary.ADSENSE);
        loadLibraries.add(LoadLibrary.DRAWING);
        loadLibraries.add(LoadLibrary.GEOMETRY);
        loadLibraries.add(LoadLibrary.PANORAMIO);
        loadLibraries.add(LoadLibrary.PLACES);
        loadLibraries.add(LoadLibrary.WEATHER);    
        loadLibraries.add(LoadLibrary.VISUALIZATION);

        Runnable onLoad = new Runnable() {
          @Override
          public void run() {
            renderMaps();
          }
        };

        LoadApi.go(onLoad, loadLibraries, sensor);
      } 

      //-------------------------------------------------------------------------------
      public void renderMaps() {
          vPanel = new VerticalPanel();

          //button to draw map on demand
          Button button = new Button("Add new map on demand");
          button.addClickHandler(new ClickHandler() {
              public void onClick(ClickEvent even) {
                  addMap();
              }
          });   
          vPanel.add(button);
          RootPanel.get("map_canvas").add(vPanel);          

          //addMap();  //adding maps programmatically works fine
          //addMap();
      }



      //-------------------------------------------------------------------------------
      private void addMap() {
          //create the map - loaded at this time    
          MapOptions myOptions = MapOptions.newInstance();
          myOptions.setZoom(7); 
          myOptions.setCenter(LatLng.newInstance(47.497909,19.040256));
          myOptions.setMapTypeId(MapTypeId.ROADMAP); 

          //MapOptions myOptions = MapOptions.newInstance(true); //same issue 

          MapWidget map = new MapWidget(myOptions);             
          map.setSize("500px", "150px");            

          vPanel.add(new Label("map " + mapCount++));
          vPanel.add(map);
      }
}
```

**Comment by branflake2267** [comment]
Does this happen during debugging with firefox?

**Comment by mgmmmm** [comment]
I am using chrome on ubuntu 12.04 with eclipse. the issue occurs in debug and also production:
I deployed a version here: http://4.mundruczo1.appspot.com/

on clicking the button twice, the first map will be fine, but the second map will be broken: the map controls look different, pan control does not work and some of the tiles are missing.

**Comment by branflake2267** [comment]
Is this what you are seeing, where tiles are missing?

![Screen Shot 2013-03-17 at 9 10 59 AM](https://f.cloud.github.com/assets/1326504/268291/5161dc58-8f1d-11e2-9bb6-f6f3287eb3f7.png)

**Comment by branflake2267** [comment]
Just after the add, try mapWidget.triggerResize();

**Comment by mgmmmm** [comment]
thanks.. all works fine!

**Comment by wikiro** [comment]
But why triggerResize() doesn't called automatically?

**Comment by branflake2267** [comment]
Good question :) I've been meaning to investigate this. I'm not sure if its the lib or the js lib yet. I have a feeling it's me, but I need to investigate further.

**Comment by twistedpair** [comment]
Ha. I used the link and saw the same missing tiles. But, when I hit F12 in Chrome to bring up the debugging menu, the browser resize fixed it, but you beat me to the answer. Nice catch @branflake2267.

**Comment by branflake2267** [comment]
:) Thanks. and thanks for looking too :)

**Comment by twistedpair** [comment]
I wanted to see if I could solve the riddle too (long compile going on at work). Do you think `MapWidget.triggerResize()` should called from [MapWidget](https://github.com/branflake2267/GWT-Maps-V3-Api/blob/master/gwt-maps-api/src/main/java/com/google/gwt/maps/client/MapWidget.java) by overriding the `onAttach` method?

**Comment by branflake2267** [comment]
I don't think that will work, b/c animation of the parent widget happens. I think observing the parent window resize or something to that manner.

**Comment by branflake2267** [comment]
So if a parent widget grows and when it finishes it has to notify the map it had resized. This would be after the onattach.
