### ISSUE TITLE
Vaadin widget

### ISSUE THREAD

**Issue by m4urer** [branflake2267/GWT-Maps-V3-Api#177]
I created a vaadin widget in order to use your jar inside Vaadin 7.
Vaadin 7 includes gwt as a core component so it should be working.
I created a widget that shows gwt native components (Button, Checkbox, etc.) without a problem, so the widget is ok. But when I add the MapWidget to the gwt VerticalLayout it doesn't show, it just leaves a blank space where the map should be.

I know this isn't an issue of your jar, and I'm sorry about that.
But maybe you have some ideas as to why it's not displaying the map. There are no errors in the console nor javascript errors. I'm using the alpha6 jar.

Could you think of any reason why other gwt components are showing ok and the map is not? Maybe some library is missing from vaadin core... maybe the script url should point somewhere else...

I hope you can throw some ideas by me because I'm lost!
Thanks in advanced!

Natalia

**Comment by branflake2267** [comment]
One options might be to check the Chrome javascript console and use it call one of the map methods to see if the maps js library is loaded. I would also inpsect the map div element to see if it has sized it self properly. It could be there, but not big enough. Those two things I find are common glitches for me.

**Comment by m4urer** [comment]
I was thinking some dependency missing or vadin/gwt compatibility issue . After your comment I focused on the JS and realized there was some duplication there! Now I can see the map!!
Thanks!!

**Comment by branflake2267** [comment]
Good job! :)
