### ISSUE TITLE
Issue with Marker.setAnimation and null

### ISSUE THREAD

**Issue by rn-a2i** [branflake2267/GWT-Maps-V3-Api#185]
Hi,

I think there is an issue with setAnimation on the Marker class, when the attribute is null (marker.setAnimation(null);).

The method checks for null, but then it invokes itself again with the same attribute as the one that was used in the first place, resulting in a inf. loop.

``` java
public final void setAnimation(Animation animation) {
    if (animation == null) {
      setAnimation(animation);
    } else {
      setAnimationImpl(animation.value());
    }
  }
```

**Comment by branflake2267** [comment]
Thanks for reporting
