### ISSUE TITLE
Map widget failing to load correctly 

### ISSUE THREAD

**Issue by magneto1** [branflake2267/GWT-Maps-V3-Api#186]
Hi I have made a map widget using gwt and have noticed some vary strange behavior. Sometime the map will load correctly and sometimes it will only half load. it loads a small area in the top left corner and then just leaves the rest of the map gray. When i press "ctrl +" the map will finish loading and work fine. Before anyone asks its not a problem with my internet connection or browser as i have checked and i commented out and extra code i put in so all it should be doing is loading the road map. Has anyone else had this problem or know what might be causing it?

![image](https://f.cloud.github.com/assets/5189002/930580/645518f8-000f-11e3-9ab9-30a77118a2fe.png)

**Comment by mgmmmm** [comment]
I believe this is the same issue as I had previously. Here is the stream and a possible fix (add a call to mapwidget.triggerResize after adding the map):
https://github.com/branflake2267/GWT-Maps-V3-Api/issues/172

**Comment by magneto1** [comment]
The problem was happening because i was setting the map widget to be invisible at the start and when it is set to visible it had the affect shown above. The call to mapwidget.triggerResize after I made the map visible solved the problem and works like a treat. Thanks for the help.
