### ISSUE TITLE
roadmap problem

### ISSUE THREAD

**Issue by ccrafael** [branflake2267/GWT-Maps-V3-Api#187]
Some countries not load the road map (Spain, Portugal, Italy ...)  when MapTypeId.ROADMAP is selected.

**Comment by branflake2267** [comment]
This is just a wrapper of the Javascript API. I'm assuming that this error is for the javascript forums.

**Comment by ccrafael** [comment]
Sorry, it was MapOptions.setMapMaker option and not a wrapper's bug.
