### ISSUE TITLE
Compilation Fails

### ISSUE THREAD

**Issue by valsoray17** [branflake2267/GWT-Maps-V3-Api#217]
I'm trying to compile GWT project (with Maps in the project) in production mode (strict) and it fails due to a 

``` bash
[ERROR] Errors in 'com/google/gwt/maps/client/drawinglib/DrawingControlOptions.java'
[ERROR] Line 72: The method toJsArrayString(String[]) is undefined for the type ArrayHelper
```

I'm using `gwt-maps-api 3.9.0-build-17` and `gwt-ajaxloader 1.1.0`. Dependencies are managed by Maven.

Am I doing something wrong?

**Comment by twistedpair** [comment]
@valsoray17 have you tried building with any of the `3.10.0` builds? Building a project of mine with `gwt-maps-api 3.9.0-build-17` works just fine in `String Mode` for me.

Please try one of the `3.10.0` builds or provide a simple configuration we can test that fails so we can investigate further. Thanks.

**Comment by valsoray17** [comment]
The 3.10.0 builds also fail in GWT STRICT mode.

Yaroslav

**Comment by valsoray17** [comment]
Seems like it's the Google's ajax-loader is not maintained anymore.

**Comment by twistedpair** [comment]
@valsoray17 Still a little puzzled here as my projects that use this lib build just fine with Maven each night. I checked on Maven Central and the [gwt-ajaxloader](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.google.gwt.google-apis%22%20AND%20a%3A%22gwt-ajaxloader%22) jar is still there, so it should be automatically downloaded and linked to satisfy the dependency problem you're facing.

Are you building with Maven? Can you share any more details of how you're compiling your project with our library? Thanks.

**Comment by valsoray17** [comment]
Sorry for a late response. I can build the project. The only problems is that if I set compiler mode to `strict` it fails to compile. Here is how to turn this option on in mvn gwt plugin:

``` java
<configuration>
    <strict>true</strict>
    ...
</configuration>
```

**Comment by twistedpair** [comment]
Glad you've managed to build the project. As it stands, we're using `strict mode` when we build the showcase. See its [pom.xml](https://github.com/branflake2267/GWT-Maps-V3-Api/blob/master/gwt-maps-showcase/pom.xml#L66-66). So, it's still not clear why you're experiencing this issue at this point. 

If anyone else has the same problem, please amend this issue. Thanks!

**Comment by valsoray17** [comment]
We had a gwt-visualization 1.0.2 coming from another dependency in the project. That's why it was causing those compilation errors. Thank you for your help.
