### ISSUE TITLE
Invisible maps on Chrome

### ISSUE THREAD

**Issue by paulux84** [branflake2267/GWT-Maps-V3-Api#226]
Hi, and thanks for your work.
All maps are now invisible on chrome...also in your demo at http://gonevertical-apis.appspot.com/.
What's the problem?

**Comment by safersystems** [comment]
All maps are visible and work OK for me on latest Chrome.

**Comment by clembo590** [comment]
the DEMO DOES NOT WORK ON CHROME Version 41.0.2272.89 (64-bit)

but it works on a old "chromium" and on firefox.

PLEASE FIX IT! IT SHOULD BE HIGHEST PRIORITY!

**Comment by paulux84** [comment]
I also have in all pc Chrome Version 41.0.2272.76 (64-bit)

**Comment by paulux84** [comment]
I've tried to pass demo url to http://www.browserstack.com/  and work an all browser and OS until Chrome version 40.xxx so the problem is definitely the version 41

**Comment by NP-85** [comment]
I've got the same problem on Chrome Version 41.0.2272.89 (64-bit)

**Comment by ottobit** [comment]
"I've got the same problem on Chrome Version 41.0.2272.89 (64-bit)"

Mee to. Same problem and same version..

**Comment by paulux84** [comment]
I've reset my settings on chrome:///flags and disabled AdBlock and now http://gonevertical-apis.appspot.com/ work... sorry!!
