### ISSUE TITLE
Google Map works on local host but doesn't work on web server

### ISSUE THREAD

**Issue by aouskaroui** [branflake2267/GWT-Maps-V3-Api#236]
Hello there,

I am working on a GWT project using this googleMap v3 Api. I was working on local host all the time and everything was good. 
Now, I deployed the project to appspot (appengine infrastructure), then everything works fine for my project except the googleMap, which actually doesn't show at all.
Is there any additional configuration that I'm supposed to do before uploading my project to the webserver or something ?

**Comment by treethinker** [comment]
It is probable that your map api key is not being honored because the domain of your new location is not authorized to it.

**Comment by aouskaroui** [comment]
That was exactly the problem. 
I was able to find more details about getting map key api on this page:
http://stackoverflow.com/questions/2769148/whats-the-api-key-for-in-google-maps-api-v3

Thank you very much !
I will mark this issue as resolved.
