### ISSUE TITLE
Event Handling in InfoWindow

### ISSUE THREAD

**Issue by rahultongia** [branflake2267/GWT-Maps-V3-Api#24]
I create a button in InfoWindow, upon clicking which an event should occur. Here is my code:

```
protected void drawInfoWindow(Marker marker, MouseEvent mouseEvent) {

    // Close the existing info window
    if (infoWindow != null) {
        infoWindow.close();
    }

    //Check for the marker
    if (marker == null || mouseEvent == null) {
        return;
    }

    //Button and HTMLPanel init
    Button infoPanelAddButton = new Button();
    HTMLPanel infoHTMLPanel;

    //Button Styling - Bootstrap
    infoPanelAddButton = new Button();
    infoPanelAddButton.setIcon(IconType.TAG);
    infoPanelAddButton.setSize(ButtonSize.DEFAULT);
    infoPanelAddButton.setType(ButtonType.SUCCESS);
    infoPanelAddButton.setText("+");

    //button click handler
    infoPanelAddButton.addClickHandler(new ClickHandler() {

        @Override
        public void onClick(ClickEvent event) {
            // TODO Auto-generated method stub

            System.out.println("Inside Here");
            Window.alert("Hello Button");
        }
    });


    //HTML Panel init and adding button
    infoHTMLPanel = new HTMLPanel(marker.getTitle());
    infoHTMLPanel.add(infoPanelAddButton);

    //InfoWindow init and content set
    InfoWindowOptions options = InfoWindowOptions.newInstance();
    infoWindow = InfoWindow.newInstance(options);

    infoWindow.setContent(infoHTMLPanel);
    infoWindow.open(map, marker);

    map.panTo(marker.getPosition());
}
```

Any ideas what can I do with the library? Or should I build my own wrapper like suggested in this http://stackoverflow.com/questions/11528637/google-maps-api-v3-buttons-and-textboxes-inside-infowindow

Thank you for the help. Btw, thanks for the very cool library.

**Comment by branflake2267** [comment]
I might be wrong, but I think your right, the infowindow seems to be limited to what we can do. I seem to remember having the same issue.

**Comment by rahultongia** [comment]
Hi @branflake2267 . Thanks for the reply. Yeah, i tried extending it but it is limited as most methods are final in the InfoWindow. For now, I simply use parameter passing on infowindow button press, much like a hyperlink. Its ugly, but thats the only one in my limited time. 

Any other idea would be cool. Thanks.

/Rahul

**Comment by branflake2267** [comment]
Hmmm. I remember asking my self that same question. I was looking at the code and I might be able to add mappanel to observe the events.

**Comment by branflake2267** [comment]
Yep that works, now to make sure whats added gets removed. I'll pull a branch in a few.

**Comment by rahultongia** [comment]
That would be cool. Thanks a lot :)

**Comment by branflake2267** [comment]
I've got a fix, I'm getting ready for pull :).

**Comment by rahultongia** [comment]
Great. Looking forward. 

Btw.. I use GWTBootstrap and with Maps lib it has an issue with 

```
    .map_canvas img {
        max-width: none;
    }
```

If I don't set this in my base css, the map wasn't rendering. However, with this it renders perfectly in chrome and safari. I still haven't figured out a way to make it work with Firefox yet. If you have something from top of your mind, would be cool, else I will fix it as I get time. My hunch is for firefox it has a need for max-width:100%, but still to try it out.

Once again thanks a lot for your help. You can preview out the map use at my app www.yumaze.com/#welcome -- still work in progress but have nice plans for it.

Cheers,
Rahul

**Comment by branflake2267** [comment]
Can you create new issue for that. Thanks. 

I have merged the pull with master. Not sure if CI will build it yet.

**Comment by branflake2267** [comment]
Closing issue, waiting for CI to build and deploy.
