### ISSUE TITLE
"public" resource are not being placed in the jar

### ISSUE THREAD

**Issue by martinlong1978** [branflake2267/GWT-Maps-V3-Api#25]
I get a lot of 404 not found in my server logs for /css/style.css.  This appears to be because the resources are declared in the module XML, but don't get included in the jar. Is this intentional?

**Comment by twistedpair** [comment]
It was a bug I had meant to chase down. I've corrected this and checked it in. Thanks for the notice.

**Comment by martinlong1978** [comment]
Great. Thanks for the quick attention. Nice work on the API.
