### ISSUE TITLE
mapOptions.scrollwheel has wrong casing

### ISSUE THREAD

**Issue by benstpierre** [branflake2267/GWT-Maps-V3-Api#28]
Take a look here

https://github.com/branflake2267/GWT-Maps-V3-Api/blob/master/Apis_Google_Maps/src/com/google/gwt/maps/client/MapOptions.java#L560

it should read

```
this.scrollwheel = scrollWheel;
```

instead of the current

```
this.scrollWheel = scrollWheel;
```

As per the documenation at google...

https://developers.google.com/maps/documentation/javascript/reference#MapOptions

> "scrollwheel   boolean If false, disables scrollwheel zooming on the map. The scrollwheel is enabled by default."

**Comment by twistedpair** [comment]
Good find. It looks like every property in the Google Maps API is camelCase, except "scrollwheel." Sorry that one slipped through. It is now corrected in the HEAD, the Showcase, and the downloadable binaries.

Let me know if you have any other issues.
