### ISSUE TITLE
JavaDocs Online

### ISSUE THREAD

**Issue by twistedpair** [branflake2267/GWT-Maps-V3-Api#29]
This is kind of a note to self to get something done. Like any good Java project, you need JavaDoc's!

**Comment by twistedpair** [comment]
So, we've had these for a while, just needed to be burnished and put into GitHub. You can now find them on the [Docs](http://branflake2267.github.com/GWT-Maps-V3-Api/javadoc/3.8.0/) page. For an exhaustive list, that will stay current in the future, see the [Wiki Docs Page](https://github.com/branflake2267/GWT-Maps-V3-Api/wiki/Docs).

**Comment by branflake2267** [comment]
Nice job on everything!
