### ISSUE TITLE
Issue detaching Panoramio layer from map

### ISSUE THREAD

**Issue by twistedpair** [branflake2267/GWT-Maps-V3-Api#38]
Originally posted on G+ by Dennis Wegewijs:

I am trying to add the panoramia layer. Adding is not a problem but removing it is using this.setMap(null). I looked at the source code of the PanoramiaLayer class and updated the following two methods to no avail. Please investigate.

**Comment by twistedpair** [comment]
The incorrect mechanism was used in the PanaramioLayer JSNI call. It has been corrected to this.setMap(map) in the commit eccd442740ce657a055ffa1dde92d2f7c8d7bd4a. I've not yet rebuilt and uploaded the jars, rebuild source if you need it. :)

**Comment by branflake2267** [comment]
Nice job. :)

**Comment by branflake2267** [comment]
Dennis uses the source, so he can fetch it.
