### ISSUE TITLE
662 @return JavaDoc statements with no arguments

### ISSUE THREAD

**Issue by twistedpair** [branflake2267/GWT-Maps-V3-Api#4]
At first I was going to just strike all of these with some Eclipse regex, since in most examples of accessors, GWT devs don't bother to restate the obvious. Clearly getValue() returns value.

However, given that exceptional return information is usually noted in this annotation, I've left them for now. The rest of the docs should be pretty clean by now.

Someone needs to plow through these occurrences  and strike/update them, or we should just strike them all in a few seconds. I'm for the later since the Maps 3.8 API Docs don't provide such exceptional return information, and if they do, we've already place it in the method comments.

**Comment by branflake2267** [comment]
I think you could strike the empties with no problem much easier than walking them. It was something that I didn't worry about and was created by eclipse when I made the comments. 

Another return note that comes to mind. Some returns have more than one value and I changed the getters getValue_Type1() and getValue_Type2() or something like that. Javascript bindings are weird for the dynamic js vars.

**Comment by twistedpair** [comment]
OK, I agree. The work vs value created ratio here would be not be favorable. I'll strike them tonight with a pinch of regex. Then I'll extirpate the remaining Javadoc compiler errors.

Where do we plan to put that Javadocs online in the future? I'll update the TC script to auto-publish them there if possible.

**Comment by branflake2267** [comment]
I was thinking somewhere around this repo on GitHub. GitHub has some sort of pages https://github.com/branflake2267/GWT-Maps-V3-Api/branches

**Comment by twistedpair** [comment]
Fixed orphaned @return statements.

**Comment by branflake2267** [comment]
nice work
