### ISSUE TITLE
Places Types Overloads Correction

### ISSUE THREAD

**Issue by cancerberoSgx** [branflake2267/GWT-Maps-V3-Api#40]
I am successfully searching places, but only can search places of type "estabhilsment", and not filtering by all the other supported by google maps places, listed at https://developers.google.com/places/documentation/supported_types. 

If I use other than "establishment" type, like "store" an java error like the following is thrown:

java.lang.IllegalArgumentException: No enum const class com.google.gwt.maps.client.placeslib.AutocompleteType.STORE

I suppose you should add all supported typen in the enumeration AutocompleteType. BTW: Why enumerations ? wouldn't be much easier to deal with strings and constants ? 

I'm using the following for searching: 

``` java
                PlaceSearchRequest req = PlaceSearchRequest.newInstance(); 
                req.setLocation(clickLocation); 
                req.setRaidus(500); 
                req.setTypes(AutocompleteType.fromValue("establishment"));

                PlacesService placeService = PlacesService.newInstance(mapWidget.getElement(), mapWidget);
                placeService.search(req, new PlaceSearchHandler() {                 
                    @Override
                    public void onCallback(JsArray<PlaceResult> results,
                            PlacesServiceStatus status) {
                        Window.alert("search result size: "+results.length()); 
                    }
                });     
```

**Comment by branflake2267** [comment]
maybe I misspelled something. hmmmm. I'll check. Thanks for the report.

**Comment by branflake2267** [comment]
```
Maybe I should add a setTypes(List<String>) :)
```

**Comment by branflake2267** [comment]
Wow, your right about the strings... I see there are hundreds of types. So I'm overloading it. 

``` java
public final void setTypes(JsArrayString types) {...}
```

**Comment by branflake2267** [comment]
I haved added an overloaded method for this. Thanks for the issue report. I also added example map, but haven't deployed it to the live demos yet. If you like to get the latest method sync to the source. Will get an updated jar available shortly. 

``` java
private void searchRequest(LatLng clickLocation) {
      String[] searchTypes = new String[1];
      searchTypes[0] = "establishment";

      JsArrayString searchJstypes = ArrayHelper.toJsArrayString(searchTypes);

      PlaceSearchRequest request = PlaceSearchRequest.newInstance(); 
    request.setLocation(clickLocation); 
    request.setRaidus(500); 
    // TODO add more AutocompleteTypes...
    //request.setTypes(AutocompleteType.ESTABLISHMENT);
    request.setTypes(searchJstypes);

    PlacesService placeService = PlacesService.newInstance(mapWidget.getElement(), mapWidget);
    placeService.search(request, new PlaceSearchHandler() {                 
        @Override
        public void onCallback(JsArray<PlaceResult> results, PlacesServiceStatus status) {
          // TODO add some popup to display the results
          Window.alert("I found this many places " + results.length());
        }
    });     
  }
```

**Comment by cancerberoSgx** [comment]
in mine jsni projects I use a method for fransforming a java array to a js array: 

```
public class JsUtil {
    public static JsArrayString toJsArrayString(String[] a) {
        if(a==null)
            return null;
        JsArrayString jsa = JsArrayNumber.createArray().<JsArrayString>cast();
        for (int i = 0; i < a.length; i++) {
            jsa.push(a[i]);
        }
        return jsa;
    }
}
```

then you can 

```
public final native void setTypes(String... types)/*-{
      @org.sgx.madrenecesidad.client.util.JsUtil::toJsArrayString([Ljava/lang/String;)(types);
}-*/;
```

and that becomes much more java friendly: 

```
req.setTypes("store", "bus_station"); 
```

or 

```
req.setTypes(PlacesService.TYPE_STORE, PlacesService.TYPE_BUSSTATION}); 
```

If I were you I would remove class AutocompleteTypes. Regards

**Comment by cancerberoSgx** [comment]
thanks for adding the method!  

PlacesService placeService = PlacesService.newInstance(mapWidget.getElement(), mapWidget);

this is wrong (my code). the map will be erased when clicked. I'm not understanding how to build a PlacesServices with your Java API. In the documentation (https://developers.google.com/maps/documentation/javascript/places#place_searches) says: 

```
service = new google.maps.places.PlacesService(map);
```

but your constructor requires 2 arguments, and in fact you are calling :

```
private static final native PlacesService createJso(Element attrContainer, MapImpl map) /*-{
    return new $wnd.google.maps.places.PlacesService(attrContainer, map);
  }-*/;
```

What is this attrContainer param ?

Regards, I will try to get the sources and  make a pull request to you with my changes.

**Comment by branflake2267** [comment]
Good point, that crossed my mind to do it that way.

**Comment by branflake2267** [comment]
That second issue... Would you mind filing that under a new issue? :)

**Comment by branflake2267** [comment]
Good idea. I'm overloading the types. :)

``` java
  public final void setTypes(List<String> types) {
    setTypes((String[]) types.toArray());
  }

  public final void setTypes(String... types) {
    setTypes(ArrayHelper.toJsArrayString(types));
  }

  public final void setTypes(JsArrayString types) {
    setTypesImpl(types);
  }
```

**Comment by branflake2267** [comment]
I pulled then merged the code with master. :)

**Comment by cancerberoSgx** [comment]
thanks! and done a second issue at https://github.com/branflake2267/GWT-Maps-V3-Api/issues/43
