### ISSUE TITLE
PlacesService bad constructor

### ISSUE THREAD

**Issue by cancerberoSgx** [branflake2267/GWT-Maps-V3-Api#43]
see it here: 
https://developers.google.com/maps/documentation/javascript/3.exp/reference#PlacesService

the PlacesService constructor accepts only one argument, an html element OR a Map object: 

```
PlacesService(attrContainer:HTMLDivElement|Map)
```

But you PlaceService Java class accept two arguments, attrContainer AND Map: 

```
private static final native PlacesService createJso(Element attrContainer, MapImpl map) /*-{
    return new $wnd.google.maps.places.PlacesService(attrContainer, map);
  }-*/;
```

This is incorrect, I would change PlacesService class to this: 

```
public class PlacesService extends JavaScriptObject {

  public static final PlacesService newInstance(MapWidget mapWidget) {
    return createJso( mapWidget.getJso());
  }
  public static final PlacesService newInstance(Element  val) {
    return createJso(val);
  }

  private static final native PlacesService createJso(Element attrContainer) /*-{
    return new $wnd.google.maps.places.PlacesService(attrContainer);
  }-*/;
  private static final native PlacesService createJso(  MapImpl map) /*-{
    return new $wnd.google.maps.places.PlacesService(map);
  }-*/;
.......
```

regards and keep the good work

**Comment by branflake2267** [comment]
Ah, I see what you mean.

**Comment by branflake2267** [comment]
Did you want to modify that and pull, or would you like me to do that?

**Comment by branflake2267** [comment]
I'm throwing it together while I'm in there.

**Comment by branflake2267** [comment]
lol, I see the relation to the other issue. :)

**Comment by branflake2267** [comment]
Fixed. :) and merged...

**Comment by cancerberoSgx** [comment]
thank you, I'm just starting with github, and if created the correction, it woul take me a lot of time., Thanks again, now trying to regenerate the jar.

**Comment by twistedpair** [comment]
cancerberoSgx, note that the most recent build of the jars are available with this fix.
