### ISSUE TITLE
git - eclipse egit issue on unix systems. 

### ISSUE THREAD

**Issue by cancerberoSgx** [branflake2267/GWT-Maps-V3-Api#45]
Hi. I'm trying to import your project using eclipse 4.2 with egit plugin on linux but I can't. (using the same steps you describe in your documenthttps://github.com/branflake2267/GWT-Maps-V3-Api/wiki/Eclipse-Contributor-Setup ). At the last step of the eclipse project import wizard, eclipse fails with the message "invalid project description". 

Researching a while about this, it seems that the the error is the following. The project name in your .project file, must be the same as the github project name. In .project file the name is "gwt-maps-api-v3" but it should be "GWT-Maps-V3-Api". See http://derekreynolds.wordpress.com/tag/git/#post-744

If you use windows perhaps you do not suffer from this bug, but in linux, file names must respect letter case. 

Regards

**Comment by branflake2267** [comment]
Try mvn eclipse:eclipse and see if that cleans the .project file?

**Comment by cancerberoSgx** [comment]
No it did not. also tried eclipse:clean and then eclipse:eclipse again. I'm not a regular maven user. I only wanted to import your project using eclipse egit like you describe in your docs, and I think this issue it is easily fixable just changing .project file from 

```
<name>gwt-maps-api-v3</name>
```

to 

```
<name>GWT-Maps-V3-Api</name>
```

(name copied and pasted exactly the same as github's)

**Comment by cancerberoSgx** [comment]
thinking the same should happen with other OSes like mac, solaris, etc....

**Comment by branflake2267** [comment]
Ah, case is wrong... hmmm, I'm on a mac, but my os is not case sensitive, wish it came that way, like ubuntu.

**Comment by branflake2267** [comment]
Want to pull that change. I won't be able to get to that until I'm finished with my job. :)

**Comment by cancerberoSgx** [comment]
yes exactly a wrong case problem... hugh, i thought macs were case senitive... thank you very much, there is no rush, then I'm planing to pull request two classes with all those hundreds of places types names as java constants, like PlaceTypes.embassy or String[] PlaceTypes.ALLTYPES. This is working nice: 

```
LatLng clickLocation = event.getMouseEvent().getLatLng(); 
PlaceSearchRequest req = PlaceSearchRequest.newInstance(); 
req.setLocation(clickLocation); 
req.setRaidus(50000); 
req.setTypes(PlaceTypes.embassy);

PlacesService placeService = PlacesService.newInstance(mapWidget);
placeService.search(req, new PlaceSearchHandler() {                 
    @Override
    public void onCallback(JsArray<PlaceResult> results,
            PlacesServiceStatus status) {
        Window.alert("embassies found in the area : "+results.length()); 
    }
});                         
```

**Comment by branflake2267** [comment]
Nice job :)
