### ISSUE TITLE
BigDecimal Use Necessary?

### ISSUE THREAD

**Issue by twistedpair** [branflake2267/GWT-Maps-V3-Api#5]
Brandon, can we strike the BigDecimal values in LatLng? Curious why they are there since they're 44 bytes in Java, and will just be converted to doubles in JS. Any reason they should stick around? Perhaps some JDO/JPA issue?

**Comment by branflake2267** [comment]
I was using them as a connivence to storing the data. You probably could remove them in this lib as I could add them on my side. I like to store and calculate them with big decimal. I think it had to do with storing them double unsigned as my coordinates would change after persist change. I've contemplated this is a few times already :)

**Comment by twistedpair** [comment]
That's what I figured. Many ORM's return BigDecimal for your to them convert to you desired type. My concern is the emulation overhead in JS and the size increase for cases where users work with large numbers of points (i.e. what I plan to do in my own app).

How about allowing a BigDecimal constructor, but otherwise using doubles internally? I'll work on that tonight.

**Comment by branflake2267** [comment]
I agree with you. I'd suggest removing it for consistency with the rest of the api. In other words I'm good with removing it.

**Comment by twistedpair** [comment]
Converted to doubles. Should run faster in JS.

Also worth noting: in Lat/Lng anything over 5 decimal places is negligible (i.e. inches), so double should be more than enough.

**Comment by branflake2267** [comment]
Good job
