### ISSUE TITLE
Typo in MapHandlerRegistration

### ISSUE THREAD

**Issue by davidnraines** [branflake2267/GWT-Maps-V3-Api#50]
I believe I see a bug / typo in the class com.google.gwt.maps.client.events.MapHandlerRegistration.  In the "removeHandlerImpl" method, one sees the line:

 $wnd.google.maps.MapsEventListener.addListener(listener);

This should read:
 $wnd.google.maps.event.removeListener(listener);

"MapsEventListener" is (I think) a relic from an older version of the code, and the "event" object is used elsewhere in the current version of MapHandlerRegistration.

I'm using GWT-Maps on my project, and I see that removing a map listener doesn't work. When I implement this change, I see that it does work. 

I've checked out a copy of GWT-Maps-V3-API with GIT, have made this change in my own checkout, and run the unit tests.  Everything seems to work.  But I wanted to enter a ticket and have some communication with the project team before I tried to commit anything.

**Comment by branflake2267** [comment]
Thanks for finding that. :)

**Comment by branflake2267** [comment]
Feel free to ask for a pull on that, and I can merge it :)

**Comment by branflake2267** [comment]
If you can't ask for pull can you let me know and I'll get on that fix. :)

**Comment by davidnraines** [comment]
I created a fork, committed my changes, and have asked for a pull.  Let me know if there's any problem.

Thanks for managing this project, these GoogleMaps GWT bindings have been very helpful!

**Comment by branflake2267** [comment]
Thanks! I merged. :)
