### ISSUE TITLE
Typo in setRadius (setRaidus)

### ISSUE THREAD

**Issue by jorgelamb** [branflake2267/GWT-Maps-V3-Api#53]
There's a typo in setRadius method in class com.google.gwt.maps.client.placeslib.PlaceSearchRequest.

I can do the fix if needed, but should I leave the old method with the typo as deprecated? Or is it ok to change it?

**Comment by branflake2267** [comment]
Good question. Why don't you deprecate and add the new one.

**Comment by jorgelamb** [comment]
Created a pull request with the change

**Comment by branflake2267** [comment]
Could you add @Deprecated over the method. Once that is done, I'll merge it. Thanks for helping out. :)

**Comment by jorgelamb** [comment]
Sure, done.

Good to help. We'll share our project when ready :)

**Comment by branflake2267** [comment]
Thank you! I merged it into master.

**Comment by branflake2267** [comment]
By the way, do you have something your building that you can share?

**Comment by jorgelamb** [comment]
We are working on a project for the Google Places API Developer Challenge, I guess you've heard of it.
https://developers.google.com/places/challenge/

The deadline is at the end of October, so it should be ready soon. We'd prefer not to make it completely public before we submit it to the contest, but we could share a link with you.

I'm not used to github, is there any private messaging in here? Or maybe direct message at twitter @jorgelamb?

**Comment by branflake2267** [comment]
It's no problem. I'm just curious. If you like, you can catch me on G+ privately, Brandon Donnelson. Have fun building it. :) Look forward to seeing what you come up with.
