### ISSUE TITLE
Support for Additional Results in Google Places search

### ISSUE THREAD

**Issue by jorgelamb** [branflake2267/GWT-Maps-V3-Api#55]
I'm looking for support of additional results in Google Places search, and I think it is not possible yet.

The API only returns up to 20 results for a search when the callback is executed, but it might have a nextPage where more results can be loaded. It needs to be executed at least two seconds after the first search, but it should be possible to access those results.

Here's the link to the documentation about this:
https://developers.google.com/maps/documentation/javascript/places#PlaceSearchPaging

tags: enhancement

**Comment by branflake2267** [comment]
Is this something you want to try to tackle or should I try to do it?

**Comment by jorgelamb** [comment]
Go for it, I don't think I'll have time for that at the moment. I'll check the status if I want to start working on it.

**Comment by branflake2267** [comment]
I'll see if I can get to it this weekend. :)

**Comment by branflake2267** [comment]
I'm working on this in 3.9 release. PlaceRequest.

**Comment by branflake2267** [comment]
I may have this done, I need to test it.

**Comment by branflake2267** [comment]
https://github.com/branflake2267/GWT-Maps-V3-Api/pull/81 - delivered.

**Comment by twistedpair** [comment]
Nice work.

**Comment by branflake2267** [comment]
Thank you :)
