### ISSUE TITLE
Is this even possible? Fusion Tables heatmap layer with radius, gradient, ...

### ISSUE THREAD

**Issue by jorgelamb** [branflake2267/GWT-Maps-V3-Api#56]
I don't know if this is even possible in Google Maps v3 API but here it goes in case someone knows:

Fusion tables configured as heatmap are very diffused when zooming in (not necessarily too much zoom, depending on the data). When zooming in trying to look for a point it is very hard to find.

There are also heatmaps where you can set the data not from a fusion table. Those heatmaps have the styling options to set the radius, gradient, opacity and so on.

In the documentation it doesn't say it's possible to add that kind of styling to a fusion table heatmap. Does anyone know if it is possible or if it doesn't work? Maybe it's just not documented.

Thanks!

labels:  question, enhancement?

Fustion tables layer documentation: https://developers.google.com/maps/documentation/javascript/3.exp/reference#FusionTablesLayer
https://developers.google.com/maps/documentation/javascript/layers#fusion_table_styles

Heatmap but not fusion table documentation: https://developers.google.com/maps/documentation/javascript/3.exp/reference?hl=en#HeatmapLayerOptions
Heatmap but not fusion table example: https://google-developers.appspot.com/maps/documentation/javascript/examples/layer-heatmap?hl=es

**Comment by branflake2267** [comment]
Great question. Maybe ask this in the javascript api group. I'm not sure this would be easy to do with the current api. Just a random thought, but what I've been wondering is if I could use svg and overlay it depending on zoom/scale. I wa thinking I could get mapserver to spit out some boundaries and some how convert the spatial polygon to use with svg. I do know mapserver can spit out overlays for google maps, but this might not be doable if on app engine.  

https://groups.google.com/forum/?fromgroups#!forum/google-maps-js-api-v3

**Comment by jorgelamb** [comment]
I tried to open a post on that Google Group but it has yet to be accepted. I'll post here if there's any update there.

**Comment by branflake2267** [comment]
Yeah, I see devrel fellow hasn't answered in a while. Maybe hes on vacation.
