### ISSUE TITLE
setDrawingMode(OverlayType drawingMode) doesn't handle null

### ISSUE THREAD

**Issue by rickdong** [branflake2267/GWT-Maps-V3-Api#57]
while in the comment, it is said that the method takes null as to reset to normal map usage. In various places such as DrawningManager and DrawingManagerOptions, this method does not handle the null case.

public final void setDrawingMode(OverlayType drawingMode) {
    setDrawingModeImpl(drawingMode.value());
}

**Comment by branflake2267** [comment]
Good point.

**Comment by branflake2267** [comment]
I copied much of the comments form the javascript lib, although when converting this has occurred. :)

**Comment by rickdong** [comment]
Seems like things we all do at times. Btw, will there be an upcoming release scheduled any time soon? Thanks.

**Comment by branflake2267** [comment]
@twistedpair Can you build a new release?

**Comment by twistedpair** [comment]
Dug around in DrawingLib and cleared that bug and some other boundary NULL cases that could potentially cause trouble. Covered all these by tests. aa6dd003d5c15e720a13226464ee91e8b5796559

Running through TeamCity right now. Will upload the revised jars tomorrow. Need to get that TeamCity/GitHub/Maven link setup so these get pushed out as nighty's.

**Comment by branflake2267** [comment]
Is this ready to close. Looks like its done.

**Comment by twistedpair** [comment]
Updated POM to version 3.8.1, did a tag and Team City build and uploaded those files since I think v3.8.0 has been beaten to death. Then working to get the final bits of v3.9 into that branch, pulling v3.8.1 up into it.

**Comment by branflake2267** [comment]
Nice job :)
