### ISSUE TITLE
no GWT application conf file in SNAPSHOT build

### ISSUE THREAD

**Issue by bambata** [branflake2267/GWT-Maps-V3-Api#6]
Hi,

this is minor stuff but I noticed that the project snapshot maven build does not have the Apis_Google_Maps.gwt.xml file in the target artifact and prevent the easy integration of the module in a gwt module.
I suggest you explicitly configure your pom to copy them at the right place in the target classes folder. 

cheers,

J.

**Comment by twistedpair** [comment]
Bambata,

Thanks for raising this issue. I had explicitly configured the build process to include this file. I'm not sure why it's not in the Jar. I'll update it tonight so that it's in there.

**Comment by bambata** [comment]
Hi twisted, 

another maven related suggestion would be to have a maven-source-plugin section in the pom to enable source attachment.I usually do this to enable including the source artifact as a dependency (to enable GWT compilation of the third party)

cheers,

J.

**Comment by twistedpair** [comment]
Thanks for the pointer. The maven-source-plugin was already setup in the project and the JavaDocs and Source are being bundled and attached. However, as you point out, the a <resource> tag is needed to add them to the Jar for GWT along with the *.gwt.xml files.

I did this and now my local copy is comping and working. Let me know if the trunk works for you. Thx.

FYI: The maven-gwt-plugin has a suggested way to do this too, but I followed their directions to no affect.
http://mojo.codehaus.org/gwt-maven-plugin/user-guide/library.html

**Comment by twistedpair** [comment]
bambata has not responded. This worked in my testing. Closing.

If anyone else has an issue, let us know.

**Comment by bambata** [comment]
Hi,

it worked for me too. Thanks
J.

On Sat, Apr 7, 2012 at 11:11 PM, Joseph Lust <
reply@reply.github.com

> wrote:
> 
> bambata has not responded. This worked in my testing. Closing.
> 
> If anyone else has an issue, let us know.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/branflake2267/GWT-Maps-V3-Api/issues/6#issuecomment-5011560

## 

Julien Abega
julien.abega@gmail.com
+33659473789

**Comment by twistedpair** [comment]
Should have been closed a few weeks back,
