### ISSUE TITLE
Maven GroupId 

### ISSUE THREAD

**Issue by branflake2267** [branflake2267/GWT-Maps-V3-Api#61]
I think we may need to come up with a better GroupId to fit sonatype hosting. Do you have any ideas?

com.google.gwt-maps-v3-api

**Comment by twistedpair** [comment]
What are the criteria?

**Comment by branflake2267** [comment]
This is a feeling as of yet, but I think sonatype might have issue we are using googles domain? Not sure yet.

**Comment by branflake2267** [comment]
I'm wondering if this will conflict with another google project. But we can see what sonatype says, if they have issue with it. 
<groupId>com.google.gwt.maps</groupId>
<artifactId>gwt-maps-api-v3</artifactId>
<version>3.8.0-beta2-SNAPSHOT</version>

**Comment by twistedpair** [comment]
True, projects like gwt-bootstrap used com.github, rather than com.twitter. I look forward to hearing what they say.

**Comment by twistedpair** [comment]
We are totally revamping our structure and our maven files for the 3.9 release. This will be released to Maven Central. You should be able to expect this within a week.

**Comment by branflake2267** [comment]
Yeah were getting quite close aren't we. :)
