### ISSUE TITLE
'Autocomplete' Exception

### ISSUE THREAD

**Issue by vbudilov** [branflake2267/GWT-Maps-V3-Api#63]
Hello!

First of all thanks for working on this framework -- awesome job!

I'm getting an exception while running your sample code at the following line: 
final Autocomplete autoComplete = Autocomplete.newInstance(element, options);

I've tested this in Chrome & Firefox (dev mode & PRD), and still get the same exception.

Can you please take a look at this?

Thanks!
Vladimir

In my HTML file:

<script src="http://maps.google.com/maps/api/js?sensor=false">
</script>

 My code:
    private void drawAutoComplete() {

```
    Element element = view.getAutocompleteElement();

    AutocompleteType[] types = new AutocompleteType[2];
    types[0] = AutocompleteType.ESTABLISHMENT;
    types[1] = AutocompleteType.GEOCODE;

    AutocompleteOptions options = AutocompleteOptions.newInstance();
    options.setTypes(types);
    options.setBounds(mapWidget.getBounds());

    final Autocomplete autoComplete = Autocomplete.newInstance(element, options);

    autoComplete.addPlaceChangeHandler(new PlaceChangeMapHandler() {
        public void onEvent(PlaceChangeMapEvent event) {

            PlaceResult result = autoComplete.getPlace();

            PlaceGeometry geomtry = result.getGeometry();
            LatLng center = geomtry.getLocation();

            InfoMessage.showInfo("Changed place: " + center.getToString());

            mapWidget.setZoom(8);

            GWT.log("place changed center=" + center);
        }
    });

    mapWidget.addBoundsChangeHandler(new BoundsChangeMapHandler() {
        public void onEvent(BoundsChangeMapEvent event) {
            LatLngBounds bounds = mapWidget.getBounds();
            autoComplete.setBounds(bounds);
        }
    });
}
```

The exception:

00:36:07.520 [ERROR] Uncaught exception escaped
com.google.gwt.event.shared.UmbrellaException: Exception caught: (TypeError) @com.google.gwt.maps.client.placeslib.Autocomplete::createJso(Lcom/google/gwt/dom/client/Element;Lcom/google/gwt/maps/client/placeslib/AutocompleteOptions;)([JavaScript object(887), JavaScript object(1216)]): $wnd.google.maps.places is undefined  at com.google.gwt.event.shared.EventBus.castFireEvent(EventBus.java:69)     at com.google.gwt.event.shared.SimpleEventBus.fireEvent(SimpleEventBus.java:57)     at com.travellinkup.ui.client.presenter.TopMenuPresenter$5.execute(TopMenuPresenter.java:134)   at com.google.gwt.user.client.ui.MenuBar$1.execute(MenuBar.java:900)    at com.google.gwt.core.client.impl.SchedulerImpl$Task$.executeScheduled$(SchedulerImpl.java:50)     at com.google.gwt.core.client.impl.SchedulerImpl.runScheduledTasks(SchedulerImpl.java:228)  at com.google.gwt.core.client.impl.SchedulerImpl.flushFinallyCommands(SchedulerImpl.java:327)   at com.google.gwt.core.client.impl.Impl.exit(Impl.java:266)     at com.google.gwt.core.client.impl.Impl.entry0(Impl.java:257)   at sun.reflect.GeneratedMethodAccessor129.invoke(Unknown Source)    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)    at java.lang.reflect.Method.invoke(Method.java:601)     at com.google.gwt.dev.shell.MethodAdaptor.invoke(MethodAdaptor.java:103)    at com.google.gwt.dev.shell.MethodDispatch.invoke(MethodDispatch.java:71)   at com.google.gwt.dev.shell.OophmSessionHandler.invoke(OophmSessionHandler.java:172)    at com.google.gwt.dev.shell.BrowserChannelServer.reactToMessages(BrowserChannelServer.java:293)     at com.google.gwt.dev.shell.BrowserChannelServer.processConnection(BrowserChannelServer.java:547)   at com.google.gwt.dev.shell.BrowserChannelServer.run(BrowserChannelServer.java:364)     at java.lang.Thread.run(Thread.java:722) Caused by: com.google.gwt.core.client.JavaScriptException: (TypeError) @com.google.gwt.maps.client.placeslib.Autocomplete::createJso(Lcom/google/gwt/dom/client/Element;Lcom/google/gwt/maps/client/placeslib/AutocompleteOptions;)([JavaScript object(887), JavaScript object(1216)]): $wnd.google.maps.places is undefined   at com.google.gwt.dev.shell.BrowserChannelServer.invokeJavascript(BrowserChannelServer.java:249)    at com.google.gwt.dev.shell.ModuleSpaceOOPHM.doInvoke(ModuleSpaceOOPHM.java:136)    at com.google.gwt.dev.shell.ModuleSpace.invokeNative(ModuleSpace.java:570)  at com.google.gwt.dev.shell.ModuleSpace.invokeNativeObject(ModuleSpace.java:278)    at com.google.gwt.dev.shell.JavaScriptHost.invokeNativeObject(JavaScriptHost.java:91)   at com.google.gwt.maps.client.placeslib.Autocomplete$.createJso(Autocomplete.java)  at com.google.gwt.maps.client.placeslib.Autocomplete$.newInstance(Autocomplete.java:32)     at com.travellinkup.ui.client.presenter.trip.QuickNewTripPresenter.drawAutoComplete(QuickNewTripPresenter.java:235)     at com.travellinkup.ui.client.presenter.trip.QuickNewTripPresenter.bind(QuickNewTripPresenter.java:104)     at com.travellinkup.ui.client.presenter.trip.QuickNewTripPresenter.go(QuickNewTripPresenter.java:92)    at com.travellinkup.ui.client.AppController.onPopupCustomPanelEvent(AppController.java:69)  at com.travellinkup.ui.client.event.PopupCustomPanelEvent.dispatch(PopupCustomPanelEvent.java:42)   at com.travellinkup.ui.client.event.PopupCustomPanelEvent.dispatch(PopupCustomPanelEvent.java:1)    at com.google.gwt.event.shared.GwtEvent.dispatch(GwtEvent.java:1)   at com.google.web.bindery.event.shared.EventBus.dispatchEvent(EventBus.java:40)     at com.google.web.bindery.event.shared.SimpleEventBus.doFire(SimpleEventBus.java:193)   at com.google.web.bindery.event.shared.SimpleEventBus.fireEvent(SimpleEventBus.java:88)     at com.google.gwt.event.shared.SimpleEventBus.fireEvent(SimpleEventBus.java:52)     at com.google.gwt.event.shared.EventBus.castFireEvent(EventBus.java:67)     at com.google.gwt.event.shared.SimpleEventBus.fireEvent(SimpleEventBus.java:57)     at com.travellinkup.ui.client.presenter.TopMenuPresenter$5.execute(TopMenuPresenter.java:134)   at com.google.gwt.user.client.ui.MenuBar$1.execute(MenuBar.java:900)    at com.google.gwt.core.client.impl.SchedulerImpl$Task$.executeScheduled$(SchedulerImpl.java:50)     at com.google.gwt.core.client.impl.SchedulerImpl.runScheduledTasks(SchedulerImpl.java:228)  at com.google.gwt.core.client.impl.SchedulerImpl.flushFinallyCommands(SchedulerImpl.java:327)   at com.google.gwt.core.client.impl.Impl.exit(Impl.java:266)     at com.google.gwt.core.client.impl.Impl.entry0(Impl.java:257)   at sun.reflect.GeneratedMethodAccessor129.invoke(Unknown Source)    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)    at java.lang.reflect.Method.invoke(Method.java:601)     at com.google.gwt.dev.shell.MethodAdaptor.invoke(MethodAdaptor.java:103)    at com.google.gwt.dev.shell.MethodDispatch.invoke(MethodDispatch.java:71)   at com.google.gwt.dev.shell.OophmSessionHandler.invoke(OophmSessionHandler.java:172)    at com.google.gwt.dev.shell.BrowserChannelServer.reactToMessages(BrowserChannelServer.java:293)     at com.google.gwt.dev.shell.BrowserChannelServer.processConnection(BrowserChannelServer.java:547)   at com.google.gwt.dev.shell.BrowserChannelServer.run(BrowserChannelServer.java:364)     at java.lang.Thread.run(Thread.java:722)

**Comment by vbudilov** [comment]
Also, I'm using GWT v2.5.0.

**Comment by branflake2267** [comment]
Just to confirm, I see the $wnd.google.maps.places is undefined. Do you have the places js loaded in the ajax loader?

**Comment by vbudilov** [comment]
You're right, I might have missed it. I'll check once I'm home. Thanks!

**Comment by branflake2267** [comment]
Sounds good. Let me know if that fixes it. :)

**Comment by vbudilov** [comment]
Fixed :) But I found a potential bug in the autocomplete functionality :) When I use autocomplete in a PopupPanel I cannot select any of the autocomplete options with the mouse, only with the keyboard. I've tested this thoroughly by putting the same exact code outside of the PopupPanel and mouse selections work. I also put your example in the PopupPanel and I get the same behavior -- mouse selections are unresponsive (putting it outside the PopupPanel works).

**Comment by branflake2267** [comment]
GWT has several issues open with popup panel, I wonder if one of them applies. Do you have modal enabled/disabled?

**Comment by vbudilov** [comment]
Yes, that was it! I just set 'modal' to false and it started working. I guess it's a GWT PopupPanel issue, rather than gwt-maps one.

**Comment by branflake2267** [comment]
Can I close this?

**Comment by vbudilov** [comment]
I'll close it. Thanks for your help! :)

**Comment by branflake2267** [comment]
Good job.

**Comment by zoewangss** [comment]
Hi odessutv,
How did you actually load the missing places library with ajax loader? 
Thanks in advance!

**Comment by branflake2267** [comment]
This is how the Places is added to the loader. 

https://github.com/branflake2267/GWT-Maps-V3-Api/blob/master/gwt-maps-showcase/src/main/java/com/google/gwt/maps/testing/client/Showcase.java#L76

**Comment by zoewangss** [comment]
Thank you!

**Comment by aouskaroui** [comment]
Hello, thanks for all this great information.
I just have another request, is it possible to add manually the places library in the ajaxloader within the GoogleMap jar ? 
Actually, I have a problem with the LoadMapApi() method. Strangely, I am able to load the map just with the draw method. Still, I can't make the Autocomplete feature work and I get the error 
"_com.google.gwt.core.client.JavaScriptException $wnd.google.maps.places is undefined_"

Thanks for any help.
