### ISSUE TITLE
How do I run the tests?

### ISSUE THREAD

**Issue by aayaffe** [branflake2267/GWT-Maps-V3-Api#74]
I have written an addition for the API, and I want to write tests for it.
However I don't even know how to run the tests you've written.
Please advise.

**Comment by branflake2267** [comment]
In eclipse, you can right click on the SandBoxTest and click on DebugAs GWT Unit Test and it should run. If you get errors the build path needs correcting.

**Comment by branflake2267** [comment]
If the SandBoxTest works, you can use that as the frame for the next test.

**Comment by branflake2267** [comment]
Let me know if you get errors and we can go from there.

**Comment by twistedpair** [comment]
Two ways:

**From Maven**
`mvn clean package` should do the trick running the tests via SureFire after compiling everything.

**From Eclipse**
Right click on `AllTestsSuite.java` and select _Run as > GWT JUnit Test_

Let us know if neither method works for you.

**Comment by aayaffe** [comment]
Thank you,
After checking "Use Google web-toolkit", in the project properties, it worked.
I was able to run all the test and add some of my own.
For some reason some if not all of the tests that check "Pan" under MapImpl and MapWidget did not pass.
I will look into it later on.

**Comment by branflake2267** [comment]
Its possible that might be inherited.

**Comment by twistedpair** [comment]
aayaffe, FYI, all 914 tests were passing last night, so your changes might have perturbed something in MapImpl. Try sycing up with the current HEAD (we just pulled in our v3.9.0 branch).
