### ISSUE TITLE
Push v3.9 Showcase to AppEngine

### ISSUE THREAD

**Issue by twistedpair** [branflake2267/GWT-Maps-V3-Api#75]
Brandon,

This does not jive anymore from Eclipse for me. I think you changed up some of the workings. Can you fix it up and push it out since you're a AppEngine pro at ArcBees?

**Comment by branflake2267** [comment]
Not sure I understand are you saying it won't load up? by the way I like the heat map. 

Yeah, one of the reasons I suggested the maven format is so we can run with the setup with this with m2e egit import. I have to modify the build path still, adding the app engine library via library button and then I sort it to below the source and be sure the jre is at the bottom of the build path. Its possible the pom needs some tuning. :)

It was working when I was doing my debugging on the places results in the 3.9.0 branch but maybe I should check again.

**Comment by branflake2267** [comment]
I see the war directory has to be set.

**Comment by branflake2267** [comment]
I'm reconfiguring the pom.xml so we can make this a two step import and run. 
gwt-maps
gwt-maps-api
gwt-maps-showcase

I'll pull it and if you have better naming you can suggest now or at the pull, the goal is to make this easy to setup. :)

**Comment by branflake2267** [comment]
I've added the google app engine deployment so team city could compile and deploy to gae too.

**Comment by branflake2267** [comment]
Ok I've got maven importing and setup complete. But is a big refactor for the first part. Its nice. I do have one quirk left with eclipse marking all my overrides and had that before, but I can't remember the fix yet, but it doesn't matter for the moment.

**Comment by twistedpair** [comment]
In m2e I believe you can hover over the exception. Use the autofix option in the exception tooltip. Just click it and it will update the POM.

**Comment by branflake2267** [comment]
I got it fixed, the compiler was setting up as 1.5 and the override annotations were getting underlined. The pom.xml variable wasn't correct b/c I messed it up.

**Comment by branflake2267** [comment]
When we are ready for this, setup your credentials in the maven settings and then try mvn gae:deploy, maybe increment one version...

**Comment by twistedpair** [comment]
You can test showcase at http://50.gonevertical-apis.appspot.com/

**Comment by branflake2267** [comment]
Nice work.
