### ISSUE TITLE
Rename module com.google.gwt.maps.Apis_Google_Maps module

### ISSUE THREAD

**Issue by branflake2267** [branflake2267/GWT-Maps-V3-Api#79]
Instead of using Apis_Google_Maps[_ForTests] maybe name it something better, since we are changing the maven repo and such. 

GitHub-GWT-Maps-API? or something that won't conflict with official...

Thoughts?

**Comment by twistedpair** [comment]
How about a much simpler name? It gets annoying typing these names out and getting them correct with case and dashes. Plus, this will need to be in the import statement people use. Given that the package name is unique enough, why not something like `Maps` or `MapsV3`?

**Comment by branflake2267** [comment]
Good idea, Sounds good to me

**Comment by twistedpair** [comment]
Done. See #86.
