### ISSUE TITLE
Rename Showcase html pages 

### ISSUE THREAD

**Issue by branflake2267** [branflake2267/GWT-Maps-V3-Api#80]
rename Apis_Maps_Test.html to Showcase.html and Apis_Maps_Test_FullPage.html to [ShowCase_FullPage.html]

Thoughts?

**Comment by twistedpair** [comment]
Sure, but not a fan of the camelCase. I've seen people get URL's wrong plenty of times this way.

**Comment by branflake2267** [comment]
Good point. I'm open to that. I wasn't worried b/c it was index or a link and I didn't see any manual typing in. Did you have any suggestions?

**Comment by twistedpair** [comment]
I was just thinking something simple like `index.html` and `fullscreen.html`. We can also host this on Github and just deploy it using the [`maven-site-plugin`](http://github.github.com/maven-plugins/site-plugin/).

**Comment by branflake2267** [comment]
Good idea. :)

**Comment by branflake2267** [comment]
Do you mean host the showcase on github?

**Comment by branflake2267** [comment]
There is some serverside code, the kml generator that wouldn't allow it to be hosted on github.

**Comment by twistedpair** [comment]
Good point, just saw that. I've done renaming in a branch.

**Comment by branflake2267** [comment]
I think that app engine gives us some more flexibility to demo server side stuff if need be.

**Comment by twistedpair** [comment]
Done. See #86
