### ISSUE TITLE
Setup TeamCity for Project on CodeBetter

### ISSUE THREAD

**Issue by twistedpair** [branflake2267/GWT-Maps-V3-Api#91]
Need to add an account on [CodeBetter](http://teamcity.codebetter.com/) for CI. Currently running off my personal machine, but this public version will allow folks to grab nightlies and to see the current master testing build state.

**Comment by twistedpair** [comment]
Filed request to add this OSS project. Currently pending.

**Comment by branflake2267** [comment]
Cool! :) `redacted` is my username.
