### ISSUE TITLE
Egit automated import didn't work

### ISSUE THREAD

**Issue by cyclingthealps** [branflake2267/GWT-Maps-V3-Api#93]
The Egit automated import did not work for me.
I had to setup the gwt-maps-showcase manually with Brandon.

**Comment by branflake2267** [comment]
What version of eclipse did you have? I forgot to ask. :)

**Comment by cyclingthealps** [comment]
Still on Indigo. Downloading Juno right now. :-)

**Comment by cancerberoSgx** [comment]
i think this could be related to mine https://github.com/branflake2267/GWT-Maps-V3-Api/issues/45. Issue was closed but file .project wasn't fixed. not sure if that can solve it...

**Comment by branflake2267** [comment]
mvn eclipse:eclipse will manually set it up. egit m2e maven import will auto import and setup the gwt plugin, if its not I need to check the pom.xml. the pom.xml should set up the gwt eclilpse plugin, but there is some maven eclipse plugin that could be used to help, but shouldn't be needed anymore.

**Comment by GaryThomas** [comment]
n.b. JAVA & Eclipse are not my forte, please excuse the noobie questions :-)

I'm trying to run the showcase [demo].  I checked out the GIT tree and have imported both the gwt-maps-api and gwt-maps-showcase projects into Eclipse (3.7.2) following the instructions above.  When I try to run to run the showcase as a GWT application, I get this error:
    [Main]: Module HTML Showcase.html does not exist

I think this is because the gwt-maps-showcase tree does not include the /war directory?

What do I need to do to make this work?

**Comment by branflake2267** [comment]
I use m2e to import the showcase which should connect the source in the build path. but it has been reported to not import correctly. I've seen this in some cases. In the maven dependencies in the navigator, there should be a item called maps-api which connects the source for the show case so a jar doesn't have to be built. The next thing to check is to see if the google webtoolkit plugin and app engine plugin is enabled by right click on the project and going to gwt or app engine. There should be a /src/main/webapp for war directory. You can double check this with the toolkit settings as well. Another thing eclipse can do is update the maven config, which I right click on project goto maven and update, which should connect up the source and such.

**Comment by branflake2267** [comment]
I wrote up some docs on this: http://c.gwt-examples.com/home/maven/ide-import/eclipse

The module is working. 

I just tried again and maven import is working good.
