### ISSUE TITLE
Update the readme.md "Eclipse Setup Using Source" part

### ISSUE THREAD

**Issue by cyclingthealps** [branflake2267/GWT-Maps-V3-Api#94]
The inherit of the module has been renamed.
Please update
<inherits name='com.google.gwt.maps.Apis_Google_Maps' />
with 
<inherits name='com.google.gwt.maps.Maps' />

**Comment by branflake2267** [comment]
Thanks for discovering that :)

**Comment by twistedpair** [comment]
I plan to do this once we've pushed to Maven Central (this week hopefully) and have cut and uploaded the release. Then we'll change them. However, I think what's on readme.md should work with v3.8.1.
