### ISSUE TITLE
Published project using GWT-Maps-V3-Api

### ISSUE THREAD

**Issue by jorgelamb** [branflake2267/GWT-Maps-V3-Api#98]
Not really an issue, but I didn't know where to put it  ;)

We've just published our project using this gwt library :) Finally, Open City Agora is published, just in time for Google Developer API Challenge. And they had extended the deadline a full month, but we can't send it with time in advance :p

You can try it from here: http://opencityagora.appspot.com

You can add layers from different sources including Open Data, Google Places, Google Maps layers and so on. Then you can save a set of layers as a View.

For the moment is only in SF and NY, but we plan to add more places.

We'd like to know what you think! Any comment is welcome.

I don't know if it is possible to add projects like this in the showcase page.

Thanks again for the library and the couple of accepted pull requests :)

Jorge

**Comment by branflake2267** [comment]
Wow nice project and great job! I'm going to look at it some more. 

Yes you can put stuff on the showcase. Fork and ask for pull request. Please add a link to your project on top too. 

Nice work.

**Comment by branflake2267** [comment]
I like the layers!

**Comment by branflake2267** [comment]
The map behaves well in your project. :)

**Comment by jorgelamb** [comment]
Thanks for the quick and good responses! It's good to read them after the
work we've done in this project :)

It's late here, we had a late submission to the contest, but I'll create
the pull request soon :D

**Comment by branflake2267** [comment]
Good job and look forward to the submission the future. No hurries. :) If you want we can link that in the read me as an implementor.

**Comment by cancerberoSgx** [comment]
Nice work @jorgelamb! I'm also trying to build something similar to your app too !  I wonder do you get all those data from google places, or from your own or other 3rd party services. If the first, what is your experience publishing new Places in google places server / service ? 

Also for @branflake2267, have this project a mailing list ? If not I think it is time, i recommend google groups. Regards

**Comment by branflake2267** [comment]
Mailing list. I have tried it, but for me its hard to manage all the source of communication I have. :) I like the Github issues, but you have a good point, not sure its busy enough yet to move to mailing list.

**Comment by jorgelamb** [comment]
@cancerberoSgx The layers come from different sources:
- Google places from Places API (via this library :)
- other Google Maps layers also from this library (transit, bike lanes, weather, ...)
- other layers come from Open Data, that we had to export to Fusion Tables to add them to the map.

You can also add advanced layers from fusion tables or kml.

About mailing list: I created here because I didn't find a better place, google groups sounds find for me.

**Comment by jorgelamb** [comment]
Hi,

I've created a pull request for adding the project to the implementers list. I didn't find something to be added to the showcase, but if you want something from there just ask for it and I'll create an example.

If you liked the project you can vote for us in the contest gallery ;) https://developers.google.com/places/challenge/gallery

Pull request created https://github.com/branflake2267/GWT-Maps-V3-Api/pull/102, I'll close this issue.

Thanks,
Jorge

**Comment by twistedpair** [comment]
@jorgelamb Nice project! :+1:
